//! The exported tool-contract snapshot equals the real binary's `tools/list` result.
//!
//! `schemas/tools.json` is generated by `cargo xtask contract update`, never hand-edited; this
//! test makes plain `cargo test` catch drift between the snapshot and the shipping binary the
//! same way `cargo xtask contract check` does in the gate.

use std::path::PathBuf;
use std::process::Stdio;

use serde_json::{Value, json};
use tokio::{
    io::{AsyncBufReadExt, AsyncWriteExt, BufReader},
    process::Command,
};

/// Distinguishes temporary endpoints across concurrently running scenarios in this process.
fn runtime() -> PathBuf {
    std::env::temp_dir().join(format!(
        "agent-ide-contract-snapshot-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|stamp| stamp.as_nanos())
            .unwrap_or(0)
    ))
}

/// Starts the shipping binary, performs the initialize handshake, and returns the `tools/list`
/// result — the same spawn shape `tests/product_mcp_contract.rs` uses.
async fn tools() -> Value {
    let mut command = Command::new(env!("CARGO_BIN_EXE_agent-ide"));
    command
        .env("TOKIO_WORKER_THREADS", "1")
        .args(["mcp", "--runtime-dir"])
        .arg(runtime())
        .env_remove("AGENT_IDE_HOST_ATTACHMENT")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true);
    let mut child = command.spawn().unwrap();
    let mut input = child.stdin.take().unwrap();
    let mut output = BufReader::new(child.stdout.take().unwrap());
    let initialize = json!({"jsonrpc":"2.0","id":1,"method":"initialize","params":{
        "protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"contract-snapshot","version":"1"}
    }});
    input
        .write_all(format!("{initialize}\n").as_bytes())
        .await
        .unwrap();
    let mut line = String::new();
    tokio::time::timeout(
        std::time::Duration::from_secs(60),
        output.read_line(&mut line),
    )
    .await
    .unwrap()
    .unwrap();
    let response: Value = serde_json::from_str(&line).unwrap();
    assert!(response.get("result").is_some(), "{response}");
    input
        .write_all(b"{\"jsonrpc\":\"2.0\",\"method\":\"notifications/initialized\"}\n")
        .await
        .unwrap();
    input
        .write_all(b"{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\",\"params\":{}}\n")
        .await
        .unwrap();
    let mut line = String::new();
    tokio::time::timeout(
        std::time::Duration::from_secs(60),
        output.read_line(&mut line),
    )
    .await
    .unwrap()
    .unwrap();
    let response: Value = serde_json::from_str(&line).unwrap();
    assert_eq!(response["id"], 2, "{response}");
    drop(input);
    let _ = child.wait().await;
    response["result"].clone()
}

/// Verifies the committed snapshot equals the binary's live `tools/list` tools array exactly.
#[tokio::test]
async fn snapshot_matches_the_binary_tools_list() {
    let result = tools().await;
    let tools = result["tools"].as_array().cloned().unwrap();
    assert_eq!(tools.len(), 11, "{result}");
    let expected: Value = serde_json::from_str(include_str!("../schemas/tools.json")).unwrap();
    assert_eq!(
        serde_json::to_value(&tools).unwrap(),
        expected,
        "contract drift: run `cargo xtask contract update` and review the diff"
    );
}
