//! Rust module parity and faults: the same MCP calls answer equally with `bundled.rust` in its
//! module and in process (`AGENT_IDE_LANGUAGE_MODE=rust=in_process`) over
//! every Rust row of the parity inventory; rust-analyzer's parent is the module, the module is a
//! direct daemon child; killing the module while rust-analyzer indexes and a `cargo check` that
//! never finishes are typed outcomes that neither restart the daemon nor leave an orphan. Needs
//! the accepted pinned 1.98.1 inputs (`AGENT_IDE_RUST_TOOLCHAIN_DIR`, `AGENT_IDE_RUST_ANALYZER`,
//! `AGENT_IDE_RUST_TOOLCHAIN`) and a binary built with `--features test-seams`.
#![cfg(feature = "test-seams")]

#[path = "support/parity.rs"]
mod parity;

use std::time::{Duration, Instant};

use parity::{Daemon, Fixture, ProcessIdentity, ProcessTree, Session, line};
use serde_json::{Value, json};

/// The fallback switch for the in-process side.
const IN_PROCESS: (&str, &str) = (parity::LANGUAGE_MODE, "rust=in_process");
/// Routes Rust to its module (the test seam until Rust ships default-on; harmless after).
const MODULE: (&str, &str) = ("AGENT_IDE_TEST_MODULE_LANGUAGES", "rust");

/// One required accepted input; there is no developer default.
fn input(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("{name} must name the accepted Rust input"))
}

/// One accepted program: path, identity and BLAKE3 of its bytes.
fn accepted(path: &str, identity: &str) -> Value {
    json!({"path":path,"identity":identity,
        "blake3":blake3::hash(&std::fs::read(path).unwrap()).to_hex().to_string()})
}

/// The launcher `providers` entry for the accepted rust-analyzer in `cache_namespace`.
fn providers(cache_namespace: &str) -> Value {
    let dir = input("AGENT_IDE_RUST_TOOLCHAIN_DIR");
    json!([{
        "executable":accepted(&input("AGENT_IDE_RUST_ANALYZER"),"rust-analyzer 1.98.1 (48a229ce 2026-09-01)"),
        "settings":"rust_cache_priming_disabled_v1",
        "toolchain":input("AGENT_IDE_RUST_TOOLCHAIN"),
        "cargo":accepted(&format!("{dir}/bin/cargo"),"cargo 1.98.1"),
        "cargo_version":"cargo 1.98.1",
        "rustc":accepted(&format!("{dir}/bin/rustc"),"rustc 1.98.1"),
        "rustc_version":"rustc 1.98.1",
        "trust":"fixture-disabled",
        "cache_namespace":cache_namespace
    }])
}

/// A committed fixture with the accepted analyzer and confined Rust checks (`check_timeout_s`).
fn rust_fixture(files: &[(&str, &str)], cache_namespace: &str, check_timeout_s: u64) -> Fixture {
    let fixture = Fixture::new(files, providers(cache_namespace));
    let mut config: Value =
        serde_json::from_slice(&std::fs::read(&fixture.config).unwrap()).unwrap();
    config["project_checks"] = json!({
        "debounce_ms":100,
        "check_timeout_s":check_timeout_s,
        "rust":{"toolchain_dir":input("AGENT_IDE_RUST_TOOLCHAIN_DIR")}
    });
    std::fs::write(&fixture.config, config.to_string()).unwrap();
    fixture
}

/// The parity crate: a type with methods, a caller chain, a unit-test module, an integration
/// test, a failing test, a warning for the check, a file the crate never compiles (module-graph
/// noncoverage), a file only the quadratic-syntax refusal sees, and a stylesheet.
const PARITY_FILES: &[(&str, &str)] = &[
    (
        "Cargo.toml",
        "[package]\nname = \"paritycrate\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    ),
    (
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"paritycrate\"\nversion = \"0.1.0\"\n",
    ),
    (
        "src/lib.rs",
        "//! Parity crate.\n\n/// A service.\npub struct Service;\n\nimpl Service {\n    /// Works.\n    pub fn work(&self) -> bool {\n        Self::helper()\n    }\n    fn helper() -> bool {\n        let unused = 1;\n        true\n    }\n}\n\npub fn user() -> bool {\n    Service.work()\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn works() {\n        assert!(user());\n    }\n}\n",
    ),
    (
        "tests/service.rs",
        "#[test]\nfn integration() {\n    assert!(paritycrate::user());\n}\n",
    ),
    (
        "tests/broken.rs",
        "#[test]\nfn fails() {\n    assert!(!paritycrate::user(), \"expected failure\");\n}\n",
    ),
    ("src/orphan.rs", "pub fn orphan() -> u8 {\n    1\n}\n"),
    (
        "src/boxed.rs",
        "pub fn boxed() -> i32 {\n    let b = box 1;\n    *b\n}\n",
    ),
    ("style.css", ".button {\n  color: red;\n}\n"),
];

/// Byte offset of `work` in the parity crate's `src/lib.rs` (its definition).
const WORK_OFFSET: usize = 96;
/// Byte offset of the `helper` call inside `Service::work`.
const HELPER_CALL_OFFSET: usize = 132;

/// Calls answered from source while rust-analyzer still loads: outline (with its marker), the
/// quadratic-syntax refusal, a symbol read and a symbol edit.
fn before_ready() -> Vec<(&'static str, Value)> {
    vec![
        ("ide.outline", json!({"path":"src/lib.rs"})),
        ("ide.outline", json!({"path":"src/boxed.rs"})),
        ("ide.read", json!({"symbol":"src/lib.rs#Service/work"})),
        (
            "ide.edit",
            json!({"operation_id":"p-early","op":"replace","symbol":"src/lib.rs#user",
            "content":"pub fn user() -> bool {\n    Service.work()\n}"}),
        ),
    ]
}

/// Calls answered by the ready analyzer, the formatter, the test runner and the card.
fn semantic() -> Vec<(&'static str, Value)> {
    let edit = |params: Value| ("ide.edit", params);
    vec![
        ("ide.start", json!({"activation_id":"parity-start"})),
        ("ide.outline", json!({"path":"src/lib.rs"})),
        (
            "ide.outline",
            json!({"path":"src/lib.rs","kinds":"fn,method"}),
        ),
        ("ide.read", json!({"path":"src/lib.rs","lines":"1-12"})),
        ("ide.symbol", json!({"symbol":"src/lib.rs#Service/work"})),
        ("ide.symbol", json!({"symbol":"helper"})),
        (
            "ide.graph",
            json!({"symbol":"src/lib.rs#user","direction":"both","depth":2}),
        ),
        (
            "ide.context",
            json!({"path":"src/lib.rs","byte_offset":HELPER_CALL_OFFSET}),
        ),
        edit(
            json!({"operation_id":"p-container","op":"insert","symbol":"src/lib.rs#tests",
            "where":"last","content":"#[test]\nfn added_test() {\n    assert!(user());\n}"}),
        ),
        edit(
            json!({"operation_id":"p-format","op":"insert","symbol":"src/lib.rs#user",
            "where":"after","content":"pub   fn added()->bool{ true }"}),
        ),
        edit(
            json!({"operation_id":"p-rename","op":"rename","symbol":"src/lib.rs#Service/work",
            "new_name":"operate"}),
        ),
        ("ide.diff", json!({})),
    ]
}

/// The `ide.test` selections: by referencing symbol, an integration binary, a failing test and a
/// name pattern.
fn test_runs() -> Vec<Value> {
    vec![
        json!({"symbol":"src/lib.rs#user"}),
        json!({"path":"tests/service.rs"}),
        json!({"path":"tests/broken.rs"}),
        json!({"pattern":"added_test"}),
    ]
}

/// One `ide.test` run: its start reply (the selected command) and, polled with `{"status": N}`
/// until it is no longer running (180 s), its settled result.
async fn test_run(session: &mut Session, fixture: &Fixture, arguments: Value) -> Vec<String> {
    let started = session.call(fixture, "ide.test", arguments.clone()).await;
    let text = started["text"].as_str().unwrap_or_default().to_owned();
    let mut lines = vec![line("ide.test", &arguments, &started)];
    let Some(id) = text
        .strip_prefix("tests #")
        .and_then(|rest| rest.split(':').next())
        .and_then(|id| id.parse::<u64>().ok())
    else {
        return lines;
    };
    let status = json!({"status":id});
    let deadline = Instant::now() + Duration::from_secs(180);
    loop {
        let reply = session.call(fixture, "ide.test", status.clone()).await;
        let text = reply["text"].as_str().unwrap_or_default();
        if !text.contains(": running") && !text.contains(": started") {
            lines.push(line("ide.test", &status, &reply));
            return lines;
        }
        assert!(
            Instant::now() < deadline,
            "tests #{id} never finished: {reply}"
        );
        tokio::time::sleep(Duration::from_millis(500)).await;
    }
}

/// `text` with every whole-second duration (`3 s`) masked: test runs report their wall time.
fn mask_seconds(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut out = String::with_capacity(text.len());
    let mut index = 0;
    while index < bytes.len() {
        let starts_word = index == 0 || !bytes[index - 1].is_ascii_alphanumeric();
        let digits = bytes[index..]
            .iter()
            .take_while(|byte| byte.is_ascii_digit())
            .count();
        let end = index + digits;
        let unit = bytes.get(end..end + 2) == Some(b" s")
            && bytes
                .get(end + 2)
                .is_none_or(|byte| !byte.is_ascii_alphanumeric());
        if starts_word && digits > 0 && unit {
            out.push_str("<seconds>");
            index = end;
        } else {
            let next = text[index..].chars().next().unwrap();
            out.push(next);
            index += next.len_utf8();
        }
    }
    out
}

/// Polls `ide.context` on `src/lib.rs` until rust-analyzer answers semantically (60 s).
async fn ready(session: &mut Session, fixture: &Fixture) {
    let deadline = Instant::now() + Duration::from_secs(60);
    loop {
        let reply = session
            .call(
                fixture,
                "ide.context",
                json!({"path":"src/lib.rs","byte_offset":WORK_OFFSET}),
            )
            .await;
        if reply["text"]
            .as_str()
            .is_some_and(|text| text.contains("mode: semantic"))
        {
            return;
        }
        assert!(
            Instant::now() < deadline,
            "rust-analyzer never ready: {reply}"
        );
        tokio::time::sleep(Duration::from_millis(250)).await;
    }
}

/// Polls Rust's problems page until `done` holds for a landed result (`limit`).
async fn problems(
    session: &mut Session,
    fixture: &Fixture,
    limit: Duration,
    done: impl Fn(&str) -> bool,
) -> String {
    let deadline = Instant::now() + limit;
    loop {
        let reply = session
            .call(
                fixture,
                "ide.context",
                json!({"kind":"problems","language":"rust"}),
            )
            .await;
        let text = reply["text"].as_str().unwrap_or_default().to_owned();
        if (!text.contains("rust: checking") && done(&text)) || Instant::now() >= deadline {
            return text;
        }
        tokio::time::sleep(Duration::from_millis(250)).await;
    }
}

/// Every descendant of `pid` with its command line, depth first.
fn descendants(pid: libc::pid_t) -> Vec<(ProcessIdentity, String)> {
    ProcessIdentity::children_of(pid)
        .into_iter()
        .flat_map(|child| std::iter::once((child, child.command())).chain(descendants(child.pid)))
        .collect()
}

/// The analyzer module that hosts rust-analyzer, with that child.
fn analyzer(tree: &ProcessTree) -> Option<(parity::Node, ProcessIdentity)> {
    tree.children
        .iter()
        .filter(|node| node.command.ends_with("module rust analyzer"))
        .find_map(|module| {
            let server = module
                .children
                .iter()
                .find(|(_, command)| command.contains("rust-analyzer"))?;
            Some((module.clone(), server.0))
        })
}

/// The transcript of one daemon run with `env`: source-first answers, the semantic and editing
/// rows, the landed project check, then an edit of a file the crate never compiles.
async fn run(fixture: &Fixture, env: &[(&str, &str)]) -> (Vec<String>, ProcessTree, Daemon) {
    let mut daemon = Daemon::start(fixture, env).await;
    let mut session = Session::start(fixture).await;
    let mut replies = Vec::new();
    for (tool, arguments) in before_ready() {
        let reply = session.call(fixture, tool, arguments.clone()).await;
        replies.push(line(tool, &arguments, &reply));
    }
    ready(&mut session, fixture).await;
    for (tool, arguments) in semantic() {
        let reply = session.call(fixture, tool, arguments.clone()).await;
        replies.push(line(tool, &arguments, &reply));
    }
    for arguments in test_runs() {
        replies.extend(test_run(&mut session, fixture, arguments).await);
    }
    replies.push(
        problems(&mut session, fixture, Duration::from_secs(120), |text| {
            text.starts_with("rust: ready")
        })
        .await,
    );
    let orphan = json!({"operation_id":"p-orphan","op":"replace","path":"src/orphan.rs",
        "lines":"2-2","content":"    2"});
    let reply = session.call(fixture, "ide.edit", orphan.clone()).await;
    replies.push(line("ide.edit", &orphan, &reply));
    let tree = daemon.tree();
    session.close(fixture).await;
    (replies, tree, daemon)
}

/// Every Rust row answers equally in the module and in process, with the process tree of §4.2:
/// in module mode rust-analyzer runs under the `module rust analyzer` child and no language
/// server is a direct daemon child; in process rust-analyzer is a direct child and no Rust
/// module runs. Nothing either daemon started survives it.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_module_and_in_process_transcripts_are_equal() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-parity", 300);
    let (local, tree, daemon) = run(&fixture, &[IN_PROCESS]).await;
    assert!(
        tree.module("rust", "analyzer").is_none() && tree.direct_child_runs("rust-analyzer"),
        "in process: rust-analyzer is a direct daemon child: {tree:?}"
    );
    let mut owned = tree.all();
    drop(daemon);
    fixture.git(&["checkout", "--quiet", "--", "."]);
    fixture.git(&["clean", "--quiet", "-fd"]);
    let (moduled, tree, daemon) = run(&fixture, &[MODULE]).await;
    let (module, _) = analyzer(&tree).expect("the analyzer module hosts rust-analyzer");
    assert!(
        !tree.direct_child_runs("rust-analyzer"),
        "no language server is a direct daemon child: {tree:?}"
    );
    assert!(module.command.ends_with("module rust analyzer"));
    // The rows the transcript must exercise, in both modes.
    for replies in [&local, &moduled] {
        let all = replies.join("\n");
        assert!(
            replies[0].contains("outline: from source"),
            "{}",
            replies[0]
        );
        assert!(replies[2].contains("work"), "{}", replies[2]);
        for (needle, row) in [
            ("mode: semantic", "semantic context"),
            ("operate", "the rename applied"),
            ("pub fn added() -> bool", "rustfmt formatted the insert"),
            ("cargo test", "cargo test selection"),
            ("1 failed", "the failing test counted"),
            ("expected failure", "libtest failure message parsed"),
            ("rust: ready", "the check landed"),
            ("unused", "the check reported the warning"),
            ("not_analysed", "module-graph noncoverage"),
        ] {
            assert!(all.contains(needle), "{row}: {needle:?} missing in\n{all}");
        }
    }
    let masked = |replies: &[String]| {
        replies
            .iter()
            .map(|reply| mask_seconds(reply))
            .collect::<Vec<_>>()
    };
    parity::assert_parity(&masked(&local), &masked(&moduled));
    owned.extend(tree.all());
    drop(daemon);
    for id in owned {
        assert!(id.gone().await, "{id:?} survived its daemon");
    }
}

/// A `cargo check` whose report exceeds 2 MiB (thousands of warnings, raw attachment bytes
/// through the checker module) lands with the same counts as in process.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn a_check_report_over_two_mib_lands_equally() {
    let many: String = (0..4000)
        .map(|index| format!("fn unused_{index}() {{}}\n"))
        .collect();
    let fixture = rust_fixture(
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"loud\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"loud\"\nversion = \"0.1.0\"\n",
            ),
            ("src/lib.rs", &many),
        ],
        "module-rust-loud",
        300,
    );
    let mut pages = Vec::new();
    for env in [IN_PROCESS, MODULE] {
        let daemon = Daemon::start(&fixture, &[env]).await;
        let mut session = Session::start(&fixture).await;
        let page = problems(&mut session, &fixture, Duration::from_secs(180), |text| {
            text.starts_with("rust: ready")
        })
        .await;
        assert!(
            page.starts_with("rust: ready; errors: 0; warnings: 4000"),
            "{page}"
        );
        pages.push(page);
        session.close(&fixture).await;
        drop(daemon);
    }
    parity::assert_parity(&pages[..1], &pages[1..]);
}

/// Killing the Rust module while rust-analyzer indexes settles the waiting semantic call with a
/// typed `module_unavailable (bundled.rust:…)` refusal; the daemon is the same process and still
/// healthy, an unrelated language answers on it, rust-analyzer dies with its module, the next
/// Rust call starts a fresh module, and nothing survives the daemon.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn killing_the_module_while_rust_analyzer_indexes_is_typed_and_leaves_no_orphan() {
    // No project check: the only typed fault in the reply is the analyzer's own.
    let fixture = Fixture::new(PARITY_FILES, providers("module-rust-kill"));
    let mut daemon = Daemon::start(&fixture, &[MODULE]).await;
    let daemon_pid = daemon.pid();
    let mut session = Session::start(&fixture).await;
    let call = json!({"symbol":"src/lib.rs#Service/work"});
    // The semantic call starts the module and rust-analyzer; it cannot answer before the
    // analyzer has loaded the workspace.
    let (fixture, outcome) = {
        let pending = tokio::spawn(async move {
            let reply = session.call(&fixture, "ide.symbol", call).await;
            (session, fixture, reply)
        });
        let deadline = Instant::now() + Duration::from_secs(30);
        let (module, server) = loop {
            if let Some(found) = analyzer(&daemon.tree()) {
                break found;
            }
            assert!(Instant::now() < deadline, "rust-analyzer never started");
            tokio::time::sleep(Duration::from_millis(20)).await;
        };
        // Indexing: rust-analyzer runs, loading the workspace, and the call is still waiting.
        tokio::time::sleep(Duration::from_millis(300)).await;
        assert!(server.exists(), "rust-analyzer is loading");
        assert!(
            !pending.is_finished(),
            "the semantic call waits for indexing"
        );
        let loading: Vec<ProcessIdentity> = descendants(module.id.pid)
            .into_iter()
            .map(|(id, _)| id)
            .collect();
        // SAFETY: `module` is the exact identity captured as this test's daemon child just now.
        unsafe { libc::kill(module.id.pid, libc::SIGKILL) };
        let (returned, fixture, reply) = pending.await.unwrap();
        session = returned;
        assert!(module.id.gone().await, "the killed module is reaped");
        for id in loading {
            assert!(id.gone().await, "{id:?} outlived its module");
        }
        (fixture, reply)
    };
    let text = outcome["text"].as_str().unwrap_or_default();
    // The symbol card keeps its definition and names why usages are missing, or the call fails
    // whole; either way its own text names the analyzer module's typed fault.
    assert!(
        outcome["code"] == "provider_unavailable" || text.contains("usages: unavailable"),
        "the original call fails its semantic part: {outcome}"
    );
    assert!(
        text.contains("module_unavailable (bundled.rust:"),
        "the original call names the module fault: {outcome}"
    );
    assert_eq!(daemon.pid(), daemon_pid, "the daemon is the same process");
    assert!(
        std::os::unix::net::UnixStream::connect(fixture.runtime.join("agent-ide.sock")).is_ok(),
        "the daemon still serves"
    );
    let unrelated = session
        .call(&fixture, "ide.outline", json!({"path":"style.css"}))
        .await;
    assert_eq!(unrelated["kind"], "outline", "{unrelated}");
    assert!(
        unrelated["text"]
            .as_str()
            .unwrap_or_default()
            .contains(".button")
    );
    // The next Rust demand starts a fresh module and answers.
    let restarted = session
        .call(&fixture, "ide.outline", json!({"path":"src/lib.rs"}))
        .await;
    assert_eq!(restarted["kind"], "outline", "{restarted}");
    let tree = daemon.tree();
    let owned = tree.all();
    session.close(&fixture).await;
    drop(daemon);
    for id in owned {
        assert!(id.gone().await, "{id:?} survived the daemon");
    }
}

/// A `cargo check` whose build script never finishes, with project checks enabled and a 10 s
/// ceiling: cargo and the build script demonstrably run, the check ends as `check timed out`
/// (never clean, never a hang), every check process is reaped, and the daemon is the same.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn a_stalled_cargo_check_times_out_and_leaves_no_orphan() {
    let fixture = rust_fixture(
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"stalled\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"stalled\"\nversion = \"0.1.0\"\n",
            ),
            (
                "build.rs",
                "fn main() { std::thread::sleep(std::time::Duration::from_secs(600)); }\n",
            ),
            ("src/lib.rs", "pub fn one() -> u8 { 1 }\n"),
        ],
        "module-rust-stall",
        10,
    );
    let mut daemon = Daemon::start(&fixture, &[MODULE]).await;
    let daemon_pid = daemon.pid();
    let mut session = Session::start(&fixture).await;
    let checking = session
        .call(
            &fixture,
            "ide.context",
            json!({"kind":"problems","language":"rust"}),
        )
        .await;
    assert!(
        checking["text"]
            .as_str()
            .is_some_and(|text| text.starts_with("rust: checking")),
        "the check runs: {checking}"
    );
    // cargo and the stalled build script run as the daemon's confined check.
    let deadline = Instant::now() + Duration::from_secs(60);
    let running = loop {
        let all = descendants(daemon_pid);
        if all
            .iter()
            .any(|(_, command)| command.contains("build-script-build"))
        {
            break all;
        }
        assert!(
            Instant::now() < deadline,
            "the build script never ran: {all:?}"
        );
        tokio::time::sleep(Duration::from_millis(100)).await;
    };
    assert!(
        running
            .iter()
            .any(|(_, command)| command.contains("/bin/cargo check")),
        "cargo runs: {running:?}"
    );
    let check: Vec<ProcessIdentity> = running
        .iter()
        .filter(|(_, command)| {
            command.contains("cargo")
                || command.contains("build-script")
                || command.contains("rustc")
        })
        .map(|(id, _)| *id)
        .collect();
    let page = problems(&mut session, &fixture, Duration::from_secs(60), |text| {
        text.starts_with("rust: check timed out")
    })
    .await;
    assert!(page.starts_with("rust: check timed out"), "{page}");
    for id in check {
        assert!(id.gone().await, "{id:?} outlived its timed-out check");
    }
    assert_eq!(daemon.pid(), daemon_pid, "the daemon is the same process");
    let owned = daemon.tree().all();
    session.close(&fixture).await;
    drop(daemon);
    for id in owned {
        assert!(id.gone().await, "{id:?} survived the daemon");
    }
}

/// The fixed offsets the transcript asks about point at the names they mean.
#[test]
fn offsets_point_at_their_names() {
    let (_, lib) = PARITY_FILES
        .iter()
        .find(|(path, _)| *path == "src/lib.rs")
        .unwrap();
    assert!(lib[WORK_OFFSET..].starts_with("work(&self)"));
    assert!(lib[HELPER_CALL_OFFSET..].starts_with("helper()\n"));
}

/// The resident memory of `id` in KiB, 0 once it is gone.
fn rss_kib(id: ProcessIdentity) -> u64 {
    let listing = std::process::Command::new("/bin/ps")
        .args(["-o", "rss=", "-p", &id.pid.to_string()])
        .output()
        .unwrap();
    String::from_utf8_lossy(&listing.stdout)
        .trim()
        .parse()
        .unwrap_or(0)
}

/// Milliseconds of one settled call that must answer `kind`.
async fn timed(
    session: &mut Session,
    fixture: &Fixture,
    tool: &str,
    arguments: Value,
    kind: &str,
) -> f64 {
    let started = Instant::now();
    let reply = session.call(fixture, tool, arguments).await;
    let elapsed = started.elapsed().as_secs_f64() * 1000.0;
    assert_eq!(reply["kind"], kind, "{reply}");
    elapsed
}

/// A measurement, not a contract (design §3.2.4): for the in-process path and the module it
/// records cold first outlines (a fresh session each), warm `ide.outline` and `ide.symbol`
/// latencies once rust-analyzer is ready, and the resident memory of the daemon's process tree,
/// written as JSON to `AGENT_IDE_MODULE_MEASURE_OUT`. Without that variable it measures nothing.
#[tokio::test]
#[ignore = "measurement; requires the accepted Rust inputs and AGENT_IDE_MODULE_MEASURE_OUT"]
async fn rust_module_measure() {
    let Some(out) = std::env::var_os("AGENT_IDE_MODULE_MEASURE_OUT").map(std::path::PathBuf::from)
    else {
        eprintln!("rust_module_measure skipped: AGENT_IDE_MODULE_MEASURE_OUT is not set");
        return;
    };
    let fixture = rust_fixture(PARITY_FILES, "module-rust-measure", 300);
    let (cold_runs, warmup, samples) = (15, 20, 200);
    let mut report = serde_json::Map::new();
    for (mode, env) in [("in_process", IN_PROCESS), ("module", MODULE)] {
        let mut daemon = Daemon::start(&fixture, &[env]).await;
        let outline = json!({"path":"src/lib.rs"});
        let symbol = json!({"symbol":"src/lib.rs#Service/work"});
        let mut cold = Vec::new();
        let mut session = Session::start(&fixture).await;
        for run in 0..cold_runs {
            if run > 0 {
                session.close(&fixture).await;
                session = Session::start(&fixture).await;
            }
            cold.push(
                timed(
                    &mut session,
                    &fixture,
                    "ide.outline",
                    outline.clone(),
                    "outline",
                )
                .await,
            );
        }
        ready(&mut session, &fixture).await;
        let mut measured = serde_json::Map::new();
        measured.insert("cold_outline_ms".into(), json!(cold));
        for (name, tool, arguments, kind) in [
            ("warm_outline_ms", "ide.outline", outline.clone(), "outline"),
            ("warm_symbol_ms", "ide.symbol", symbol.clone(), "symbol"),
        ] {
            for _ in 0..warmup {
                timed(&mut session, &fixture, tool, arguments.clone(), kind).await;
            }
            let mut values = Vec::new();
            for _ in 0..samples {
                values.push(timed(&mut session, &fixture, tool, arguments.clone(), kind).await);
            }
            measured.insert(name.into(), json!(values));
        }
        let tree = daemon.tree();
        let mut memory = vec![
            json!({"process":"daemon","rss_kib":rss_kib(ProcessIdentity::of(daemon.pid()).unwrap().0)}),
        ];
        for node in &tree.children {
            memory.push(json!({"process":node.command,"rss_kib":rss_kib(node.id)}));
            for (id, command) in &node.children {
                memory.push(json!({"process":format!("  {command}"),"rss_kib":rss_kib(*id)}));
            }
        }
        measured.insert("rss".into(), json!(memory));
        report.insert(mode.into(), Value::Object(measured));
        session.close(&fixture).await;
        drop(daemon);
    }
    report.insert(
        "method".into(),
        json!({"cold_runs": cold_runs, "warmup": warmup, "calls": samples,
               "clock": "wall time of one settled MCP tools/call round trip measured in the test process"}),
    );
    std::fs::write(
        &out,
        serde_json::to_vec_pretty(&Value::Object(report)).unwrap(),
    )
    .unwrap();
}

/// The module fault seam (`agent_ide_core::modules::serve::FAULT_SEAM`).
const FAULT_SEAM: &str = "AGENT_IDE_TEST_MODULE_FAULT";
/// The module request budget seam (`agent_ide_core::modules::router::BUDGET_SEAM`).
const BUDGET_SEAM: &str = "AGENT_IDE_TEST_MODULE_BUDGET_MS";

/// The M-A conformance cases on the Rust analyzer module with the real rust-analyzer: once the
/// analyzer is ready, a stall past the module budget and a malformed reply each settle the next
/// semantic call with a typed `module_unavailable (bundled.rust:…)` (timeout, malformed) on the
/// same healthy daemon, and the following call starts a fresh module that answers semantically;
/// neither the failed module nor its rust-analyzer survives.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_analyzer_seam_faults_are_typed_and_restart() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-seams", 300);
    let usages = json!({"symbol":"src/lib.rs#Service/work"});
    for (fault, cause) in [("stall", "timeout"), ("malformed", "malformed")] {
        // The flag is created only once the analyzer is ready, so the seam fires on the next
        // semantic request rather than on the warm-up.
        let flag = fixture.base.join(format!("rust-module-fault-{fault}"));
        let seam = format!("{fault}:semantic:{}", flag.display());
        let mut daemon = Daemon::start(
            &fixture,
            &[MODULE, (FAULT_SEAM, &seam), (BUDGET_SEAM, "5000")],
        )
        .await;
        let daemon_pid = daemon.pid();
        let mut session = Session::start(&fixture).await;
        ready(&mut session, &fixture).await;
        let (first, server) = analyzer(&daemon.tree()).expect("the analyzer module runs");
        std::fs::write(&flag, "").unwrap();
        let started = Instant::now();
        let failed = session.call(&fixture, "ide.symbol", usages.clone()).await;
        let failed_after = started.elapsed();
        assert!(!flag.exists(), "{fault}: the seam fired");
        assert!(
            failed
                .to_string()
                .contains("module_unavailable (bundled.rust:")
                && failed.to_string().contains(cause),
            "{fault}: the call names the typed module fault: {failed}"
        );
        assert!(
            failed_after < Duration::from_secs(30),
            "{fault} answered after {failed_after:?}"
        );
        assert!(first.id.gone().await, "{fault}: the failed module survived");
        assert!(server.gone().await, "{fault}: its rust-analyzer survived");
        ready(&mut session, &fixture).await;
        let (second, _) = analyzer(&daemon.tree()).expect("a fresh analyzer module runs");
        assert_ne!(
            first.id, second.id,
            "{fault}: the failed module was replaced"
        );
        assert_eq!(daemon.pid(), daemon_pid, "{fault}: same daemon");
        let owned = daemon.tree().all();
        session.close(&fixture).await;
        drop(daemon);
        for id in owned {
            assert!(id.gone().await, "{fault}: {id:?} survived the daemon");
        }
    }
}

/// The M-A conformance cases on the Rust checker module: a stall past the budget, a malformed
/// reply and a `kill -9` of the checker module each leave Rust's check `check failed` naming
/// `module_unavailable (bundled.rust:…)`, never clean; after an edit the next check starts a
/// fresh module and lands, on the same daemon.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_checker_seam_faults_are_typed_and_restart() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-check-seams", 30);
    for (fault, expected) in [
        ("stall", "module_unavailable (bundled.rust:request:timeout)"),
        (
            "malformed",
            "module_unavailable (bundled.rust:request:malformed)",
        ),
        ("kill", "module_unavailable (bundled.rust:request:exited)"),
    ] {
        let flag = fixture.base.join(format!("rust-check-fault-{fault}"));
        std::fs::write(&flag, "").unwrap();
        let kind = if fault == "malformed" {
            "malformed"
        } else {
            "stall"
        };
        let seam = format!("{kind}:check_plan:{}", flag.display());
        let mut daemon = Daemon::start(
            &fixture,
            &[MODULE, (FAULT_SEAM, &seam), (BUDGET_SEAM, "3000")],
        )
        .await;
        let daemon_pid = daemon.pid();
        let mut session = Session::start(&fixture).await;
        if fault == "kill" {
            let deadline = Instant::now() + Duration::from_secs(30);
            let checker = loop {
                if let Some(node) = daemon.tree().module("rust", "checker").cloned()
                    && !flag.exists()
                {
                    break node;
                }
                assert!(Instant::now() < deadline, "the stalled checker never ran");
                tokio::time::sleep(Duration::from_millis(50)).await;
            };
            // SAFETY: the exact module identity captured as this test's daemon child just now.
            unsafe { libc::kill(checker.id.pid, libc::SIGKILL) };
        }
        let failed = problems(&mut session, &fixture, Duration::from_secs(60), |text| {
            text.contains(expected)
        })
        .await;
        assert!(
            failed.starts_with("rust: check failed") && failed.contains(expected),
            "{fault}: the check names the fault:\n{failed}"
        );
        std::fs::write(
            fixture.root.join("src/lib.rs"),
            format!("pub fn edited_{fault}() -> u8 {{\n    1\n}}\n"),
        )
        .unwrap();
        let landed = problems(&mut session, &fixture, Duration::from_secs(120), |text| {
            text.starts_with("rust: ready")
        })
        .await;
        assert!(
            landed.starts_with("rust: ready"),
            "{fault}: the next check lands:\n{landed}"
        );
        assert_eq!(daemon.pid(), daemon_pid, "{fault}: same daemon");
        session.close(&fixture).await;
        drop(daemon);
        fixture.git(&["checkout", "--quiet", "--", "."]);
    }
}

/// The Rust analyzer module shares the supervised slots' restart policy: after the initial
/// start and three restarts within the window (each death settled typed on the next demand),
/// a further demand is refused `restart_exhausted` (typed, on the same daemon) and no fifth
/// module starts.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_analyzer_crash_loop_exhausts_the_restart_budget() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-crash-loop", 300);
    let mut daemon = Daemon::start(&fixture, &[MODULE]).await;
    let daemon_pid = daemon.pid();
    let mut session = Session::start(&fixture).await;
    let outline = json!({"path":"src/lib.rs"});
    let context = json!({"path":"src/lib.rs","byte_offset":WORK_OFFSET});
    // Deaths are noticed through the backend's own path (context) and through the core's
    // semantic paths (symbol, graph); each counts once against the same budget.
    let demands = [
        ("ide.context", context.clone()),
        ("ide.symbol", json!({"symbol":"src/lib.rs#Service/work"})),
        ("ide.graph", json!({"symbol":"src/lib.rs#user"})),
        ("ide.symbol", json!({"symbol":"src/lib.rs#user"})),
    ];
    for attempt in 0..4 {
        // A demand starts the module (the first after a death is settled with its fault).
        let (tool, arguments) = &demands[attempt];
        let deadline = Instant::now() + Duration::from_secs(30);
        let module = loop {
            let _ = session.call(&fixture, tool, arguments.clone()).await;
            if let Some((module, _)) = analyzer(&daemon.tree()) {
                break module;
            }
            assert!(
                Instant::now() < deadline,
                "attempt {attempt}: no analyzer module"
            );
        };
        // SAFETY: the exact module identity captured as a child of this test's daemon.
        unsafe { libc::kill(module.id.pid, libc::SIGKILL) };
        assert!(module.id.gone().await);
        // Let each backoff (250 ms, 1 s, 4 s) pass so the next start really happens.
        tokio::time::sleep(Duration::from_millis([300, 1100, 4100, 0][attempt])).await;
    }
    let mut refused = Value::Null;
    for _ in 0..3 {
        refused = session.call(&fixture, "ide.context", context.clone()).await;
        if refused.to_string().contains("restart_exhausted") {
            break;
        }
    }
    assert!(
        refused.to_string().contains("restart_exhausted"),
        "a demand names the exhausted budget: {refused}"
    );
    assert!(
        analyzer(&daemon.tree()).is_none(),
        "no fifth module started"
    );
    let lexical = session.call(&fixture, "ide.outline", outline).await;
    assert_eq!(
        lexical["kind"], "outline",
        "outline still answers from source: {lexical}"
    );
    assert_eq!(daemon.pid(), daemon_pid, "same daemon");
    session.close(&fixture).await;
}

/// Whole-second durations are masked wherever they stand; other numbers stay.
#[test]
fn seconds_are_masked_and_nothing_else() {
    assert_eq!(
        mask_seconds("tests #2: 1 passed, 1 failed, 3 s\nbudget 120 s; 12 sec, a1 s, 4 s."),
        "tests #2: 1 passed, 1 failed, <seconds> s\nbudget <seconds> s; 12 sec, a1 s, <seconds> s."
    );
}
