//! Rust module parity and faults: the same MCP calls answer equally with `bundled.rust` in its
//! module and in process (`AGENT_IDE_LANGUAGE_MODE=rust=in_process`) over
//! every Rust row of the parity inventory; rust-analyzer's parent is the module, the module is a
//! direct daemon child; killing the module while rust-analyzer indexes and a `cargo check` that
//! never finishes are typed outcomes that neither restart the daemon nor leave an orphan. Needs
//! the accepted pinned 1.98.1 inputs (`AGENT_IDE_RUST_TOOLCHAIN_DIR`, `AGENT_IDE_RUST_ANALYZER`,
//! `AGENT_IDE_RUST_TOOLCHAIN`) and a binary built with `--features test-seams`.
#![cfg(feature = "test-seams")]

#[path = "support/parity.rs"]
mod parity;

use std::time::{Duration, Instant};

use parity::{Daemon, Fixture, ProcessIdentity, ProcessTree, Session};
use serde_json::{Value, json};

/// The fallback switch for the in-process side.
const IN_PROCESS: (&str, &str) = (parity::LANGUAGE_MODE, "rust=in_process");
/// Routes Rust to its module (the test seam until Rust ships default-on; harmless after).
const MODULE: (&str, &str) = ("AGENT_IDE_TEST_MODULE_LANGUAGES", "rust");

/// One required accepted input; there is no developer default.
fn input(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("{name} must name the accepted Rust input"))
}

/// One accepted program: path, identity and BLAKE3 of its bytes.
fn accepted(path: &str, identity: &str) -> Value {
    json!({"path":path,"identity":identity,
        "blake3":blake3::hash(&std::fs::read(path).unwrap()).to_hex().to_string()})
}

/// The launcher `providers` entry for the accepted rust-analyzer in `cache_namespace`.
fn providers(cache_namespace: &str) -> Value {
    let dir = input("AGENT_IDE_RUST_TOOLCHAIN_DIR");
    json!([{
        "executable":accepted(&input("AGENT_IDE_RUST_ANALYZER"),"rust-analyzer 1.98.1 (48a229ce 2026-09-01)"),
        "settings":"rust_cache_priming_disabled_v1",
        "toolchain":input("AGENT_IDE_RUST_TOOLCHAIN"),
        "cargo":accepted(&format!("{dir}/bin/cargo"),"cargo 1.98.1"),
        "cargo_version":"cargo 1.98.1",
        "rustc":accepted(&format!("{dir}/bin/rustc"),"rustc 1.98.1"),
        "rustc_version":"rustc 1.98.1",
        "trust":"fixture-disabled",
        "cache_namespace":cache_namespace
    }])
}

/// A committed fixture with the accepted analyzer and confined Rust checks (`check_timeout_s`).
fn rust_fixture(files: &[(&str, &str)], cache_namespace: &str, check_timeout_s: u64) -> Fixture {
    let fixture = Fixture::new(files, providers(cache_namespace));
    let mut config: Value =
        serde_json::from_slice(&std::fs::read(&fixture.config).unwrap()).unwrap();
    config["project_checks"] = json!({
        "debounce_ms":100,
        "check_timeout_s":check_timeout_s,
        "rust":{"toolchain_dir":input("AGENT_IDE_RUST_TOOLCHAIN_DIR")}
    });
    std::fs::write(&fixture.config, config.to_string()).unwrap();
    fixture
}

/// The parity crate: a type with methods, a caller chain, a unit-test module, an integration
/// test, a failing test, a warning for the check, a file the crate never compiles (module-graph
/// noncoverage), a file only the quadratic-syntax refusal sees, and a stylesheet.
const PARITY_FILES: &[(&str, &str)] = &[
    (
        "Cargo.toml",
        "[package]\nname = \"paritycrate\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    ),
    (
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"paritycrate\"\nversion = \"0.1.0\"\n",
    ),
    (
        "src/lib.rs",
        "//! Parity crate.\n\n/// A service.\npub struct Service;\n\nimpl Service {\n    /// Works.\n    pub fn work(&self) -> bool {\n        Self::helper()\n    }\n    fn helper() -> bool {\n        let unused = 1;\n        true\n    }\n}\n\npub fn user() -> bool {\n    Service.work()\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn works() {\n        assert!(user());\n    }\n}\n",
    ),
    (
        "tests/service.rs",
        "#[test]\nfn integration() {\n    assert!(paritycrate::user());\n}\n",
    ),
    (
        "tests/broken.rs",
        "#[test]\nfn fails() {\n    assert!(!paritycrate::user(), \"expected failure\");\n}\n",
    ),
    ("src/orphan.rs", "pub fn orphan() -> u8 {\n    1\n}\n"),
    (
        "src/boxed.rs",
        "pub fn boxed() -> i32 {\n    let b = box 1;\n    *b\n}\n",
    ),
    ("style.css", ".button {\n  color: red;\n}\n"),
];

/// Byte offset of `work` in the parity crate's `src/lib.rs` (its definition).
const WORK_OFFSET: usize = 96;
/// Byte offset of the `helper` call inside `Service::work`.
const HELPER_CALL_OFFSET: usize = 132;

/// Calls answered from source while rust-analyzer still loads: outline (with its marker), the
/// quadratic-syntax refusal, a symbol read and a symbol edit.
fn before_ready() -> Vec<(&'static str, Value)> {
    vec![
        ("ide.outline", json!({"path":"src/lib.rs"})),
        ("ide.outline", json!({"path":"src/boxed.rs"})),
        ("ide.read", json!({"symbol":"src/lib.rs#Service/work"})),
        (
            "ide.edit",
            json!({"operation_id":"p-early","op":"replace","symbol":"src/lib.rs#user",
            "content":"pub fn user() -> bool {\n    Service.work()\n}"}),
        ),
    ]
}

/// Calls answered by the ready analyzer, the formatter, the test runner and the card.
fn semantic() -> Vec<(&'static str, Value)> {
    let edit = |params: Value| ("ide.edit", params);
    vec![
        ("ide.start", json!({"activation_id":"parity-start"})),
        ("ide.outline", json!({"path":"src/lib.rs"})),
        (
            "ide.outline",
            json!({"path":"src/lib.rs","kinds":"fn,method"}),
        ),
        ("ide.read", json!({"path":"src/lib.rs","lines":"1-12"})),
        ("ide.symbol", json!({"symbol":"src/lib.rs#Service/work"})),
        ("ide.symbol", json!({"symbol":"helper"})),
        (
            "ide.graph",
            json!({"symbol":"src/lib.rs#user","direction":"both","depth":2}),
        ),
        (
            "ide.context",
            json!({"path":"src/lib.rs","byte_offset":HELPER_CALL_OFFSET}),
        ),
        edit(
            json!({"operation_id":"p-container","op":"insert","symbol":"src/lib.rs#tests",
            "where":"last","content":"#[test]\nfn added_test() {\n    assert!(user());\n}"}),
        ),
        edit(
            json!({"operation_id":"p-format","op":"insert","symbol":"src/lib.rs#user",
            "where":"after","content":"pub   fn added()->bool{ true }"}),
        ),
        edit(
            json!({"operation_id":"p-rename","op":"rename","symbol":"src/lib.rs#Service/work",
            "new_name":"operate"}),
        ),
        ("ide.diff", json!({})),
    ]
}

/// One transcript entry: the harness line with the fixture root written as `<root>`, followed for
/// an edit (whose reply carries no text) by its structured reply. An edit's `status` plate is
/// left out: it carries whatever check result happens to be due at that moment.
fn record(fixture: &Fixture, tool: &str, arguments: &Value, reply: &Value) -> String {
    let mut arguments = arguments.clone();
    mask_refs(&mut arguments);
    let mut entry = parity::line_for(fixture, tool, &arguments, reply);
    if tool == "ide.edit" {
        let mut body = reply.clone();
        if let Some(object) = body.as_object_mut() {
            object.remove("status");
        }
        mask_refs(&mut body);
        entry.push('\n');
        entry.push_str(
            &body
                .to_string()
                .replace(&fixture.root.display().to_string(), "<root>"),
        );
    }
    entry
}

/// Masks the per-daemon opaque references (`source_ref`, `detail_ref` string values) anywhere in
/// a structured reply; a null or missing reference keeps its shape, every other value stays.
fn mask_refs(value: &mut Value) {
    match value {
        Value::Object(object) => {
            for (key, field) in object.iter_mut() {
                if matches!(key.as_str(), "source_ref" | "detail_ref") && field.is_string() {
                    *field = Value::String("<ref>".to_owned());
                } else {
                    mask_refs(field);
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(mask_refs),
        _ => {}
    }
}

/// The `ide.test` selections: by referencing symbol, an integration binary, a failing test and a
/// name pattern.
fn test_runs() -> Vec<Value> {
    vec![
        json!({"symbol":"src/lib.rs#user"}),
        json!({"path":"tests/service.rs"}),
        json!({"path":"tests/broken.rs"}),
        json!({"pattern":"added_test"}),
    ]
}

/// One `ide.test` run: its start reply (the selected command) and, polled with `{"status": N}`
/// until it is no longer running (180 s), its settled result.
async fn test_run(session: &mut Session, fixture: &Fixture, arguments: Value) -> Vec<String> {
    let started = session.call(fixture, "ide.test", arguments.clone()).await;
    let text = started["text"].as_str().unwrap_or_default().to_owned();
    let mut lines = vec![record(fixture, "ide.test", &arguments, &started)];
    let Some(id) = text
        .strip_prefix("tests #")
        .and_then(|rest| rest.split(':').next())
        .and_then(|id| id.parse::<u64>().ok())
    else {
        return lines;
    };
    let status = json!({"status":id});
    let deadline = Instant::now() + Duration::from_secs(180);
    loop {
        let reply = session.call(fixture, "ide.test", status.clone()).await;
        let text = reply["text"].as_str().unwrap_or_default();
        if !text.contains(": running") && !text.contains(": started") {
            lines.push(record(fixture, "ide.test", &status, &reply));
            return lines;
        }
        assert!(
            Instant::now() < deadline,
            "tests #{id} never finished: {reply}"
        );
        tokio::time::sleep(Duration::from_millis(500)).await;
    }
}

/// `text` with the elapsed wall time of each `ide.test` result line masked (`tests #2: 1 passed,
/// 1 failed, 3 s` -> `…, <seconds> s`); budgets and every other number stay byte-compared.
fn mask_seconds(text: &str) -> String {
    text.split('\n')
        .map(|line| {
            if !line.starts_with("tests #") {
                return line.to_owned();
            }
            let mut masked = String::with_capacity(line.len());
            let mut rest = line;
            while let Some(at) = rest.find(", ") {
                masked.push_str(&rest[..at + 2]);
                rest = &rest[at + 2..];
                let digits = rest.bytes().take_while(u8::is_ascii_digit).count();
                let after = &rest[digits..];
                let elapsed = digits > 0
                    && after.starts_with(" s")
                    && after[2..]
                        .chars()
                        .next()
                        .is_none_or(|next| !next.is_alphanumeric());
                if elapsed {
                    masked.push_str("<seconds>");
                    rest = after;
                }
            }
            masked.push_str(rest);
            masked
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Polls `ide.context` on `src/lib.rs` until rust-analyzer answers semantically (60 s).
async fn ready(session: &mut Session, fixture: &Fixture) {
    let deadline = Instant::now() + Duration::from_secs(60);
    loop {
        let reply = session
            .call(
                fixture,
                "ide.context",
                json!({"path":"src/lib.rs","byte_offset":WORK_OFFSET}),
            )
            .await;
        if reply["text"]
            .as_str()
            .is_some_and(|text| text.contains("mode: semantic"))
        {
            return;
        }
        if Instant::now() >= deadline {
            // The symbol card names a typed module failure the lexical context answer does not.
            let card = session
                .call(
                    fixture,
                    "ide.symbol",
                    json!({"symbol":"src/lib.rs#Service/work"}),
                )
                .await;
            panic!("rust-analyzer never ready: {reply}\nsymbol card: {card}");
        }
        tokio::time::sleep(Duration::from_millis(250)).await;
    }
}

/// Polls Rust's problems page until `done` holds for a landed result (`limit`).
async fn problems(
    session: &mut Session,
    fixture: &Fixture,
    limit: Duration,
    done: impl Fn(&str) -> bool,
) -> String {
    let deadline = Instant::now() + limit;
    loop {
        let reply = session
            .call(
                fixture,
                "ide.context",
                json!({"kind":"problems","language":"rust"}),
            )
            .await;
        let text = reply["text"].as_str().unwrap_or_default().to_owned();
        if (!text.contains("rust: checking") && done(&text)) || Instant::now() >= deadline {
            return text;
        }
        tokio::time::sleep(Duration::from_millis(250)).await;
    }
}

/// Every descendant of `pid` with its command line, depth first.
fn descendants(pid: libc::pid_t) -> Vec<(ProcessIdentity, String)> {
    ProcessIdentity::children_of(pid)
        .into_iter()
        .flat_map(|child| std::iter::once((child, child.command())).chain(descendants(child.pid)))
        .collect()
}

/// The analyzer module that hosts rust-analyzer, with that child.
fn analyzer(tree: &ProcessTree) -> Option<(parity::Node, ProcessIdentity)> {
    tree.children
        .iter()
        .filter(|node| node.command.ends_with("module rust analyzer"))
        .find_map(|module| {
            let server = module
                .children
                .iter()
                .find(|(_, command)| command.contains("rust-analyzer"))?;
            Some((module.clone(), server.0))
        })
}

/// The transcript of one daemon run with `env`: source-first answers, the semantic and editing
/// rows, the landed project check, then an edit of a file the crate never compiles.
async fn run(fixture: &Fixture, env: &[(&str, &str)]) -> (Vec<String>, ProcessTree, Daemon) {
    let mut daemon = Daemon::start(fixture, env).await;
    let mut session = Session::start(fixture).await;
    let mut replies = Vec::new();
    for (tool, arguments) in before_ready() {
        let reply = session.call(fixture, tool, arguments.clone()).await;
        replies.push(record(fixture, tool, &arguments, &reply));
    }
    ready(&mut session, fixture).await;
    for (tool, arguments) in semantic() {
        let reply = session.call(fixture, tool, arguments.clone()).await;
        replies.push(record(fixture, tool, &arguments, &reply));
    }
    for arguments in test_runs() {
        replies.extend(test_run(&mut session, fixture, arguments).await);
    }
    replies.push(
        problems(&mut session, fixture, Duration::from_secs(120), |text| {
            text.starts_with("rust: ready")
        })
        .await,
    );
    let read = json!({"path":"src/orphan.rs","lines":"1-3"});
    let observed = session.call(fixture, "ide.read", read.clone()).await;
    replies.push(record(fixture, "ide.read", &read, &observed));
    let orphan = json!({"operation_id":"p-orphan","op":"replace","path":"src/orphan.rs",
        "lines":"2-2","content":"    2","source_ref":observed["detail_ref"]});
    let reply = session.call(fixture, "ide.edit", orphan.clone()).await;
    replies.push(record(fixture, "ide.edit", &orphan, &reply));
    let tree = daemon.tree();
    session.close(fixture).await;
    (replies, tree, daemon)
}

/// Every Rust row answers equally in the module and in process, with the process tree of §4.2:
/// in module mode rust-analyzer runs under the `module rust analyzer` child and no language
/// server is a direct daemon child; in process rust-analyzer is a direct child and no Rust
/// module runs. Nothing either daemon started survives it.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_module_and_in_process_transcripts_are_equal() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-parity", 300);
    let (local, tree, daemon) = run(&fixture, &[IN_PROCESS]).await;
    assert!(
        tree.module("rust", "analyzer").is_none() && tree.direct_child_runs("rust-analyzer"),
        "in process: rust-analyzer is a direct daemon child: {tree:?}"
    );
    let mut owned = tree.all();
    drop(daemon);
    fixture.git(&["checkout", "--quiet", "--", "."]);
    fixture.git(&["clean", "--quiet", "-fd"]);
    let (moduled, tree, daemon) = run(&fixture, &[MODULE]).await;
    let (module, _) = analyzer(&tree).expect("the analyzer module hosts rust-analyzer");
    assert!(
        !tree.direct_child_runs("rust-analyzer"),
        "no language server is a direct daemon child: {tree:?}"
    );
    assert!(module.command.ends_with("module rust analyzer"));
    // The rows the transcript must exercise, in both modes.
    for replies in [&local, &moduled] {
        let all = replies.join("\n");
        assert!(
            replies[0].contains("outline: from source"),
            "{}",
            replies[0]
        );
        assert!(replies[2].contains("work"), "{}", replies[2]);
        for (needle, row) in [
            ("mode: semantic", "semantic context"),
            ("operate", "the rename applied"),
            ("pub fn added() -> bool", "rustfmt formatted the insert"),
            ("cargo test", "cargo test selection"),
            ("1 failed", "the failing test counted"),
            ("expected failure", "libtest failure message parsed"),
            ("rust: ready", "the check landed"),
            ("unused", "the check reported the warning"),
            ("not_analysed", "module-graph noncoverage"),
        ] {
            assert!(all.contains(needle), "{row}: {needle:?} missing in\n{all}");
        }
    }
    let masked = |replies: &[String]| {
        replies
            .iter()
            .map(|reply| mask_text_refs(&mask_counters(&mask_seconds(reply))))
            .collect::<Vec<_>>()
    };
    let (local, moduled) = (masked(&local), masked(&moduled));
    // Every differing pair at once (the shared assertion stops at the first).
    let differing: Vec<String> = local
        .iter()
        .zip(&moduled)
        .filter(|(left, right)| parity::normalized(left) != parity::normalized(right))
        .map(|(left, right)| format!("--- in process ---\n{left}\n--- module ---\n{right}"))
        .collect();
    assert!(
        differing.is_empty(),
        "{} differing replies:\n{}",
        differing.len(),
        differing.join("\n")
    );
    parity::assert_parity(&local, &moduled);
    owned.extend(tree.all());
    drop(daemon);
    for id in owned {
        assert!(id.gone().await, "{id:?} survived its daemon");
    }
}

/// A `cargo check` whose report exceeds 2 MiB (thousands of warnings, raw attachment bytes
/// through the checker module) lands with the same counts as in process.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn a_check_report_over_two_mib_lands_equally() {
    let many: String = (0..4000)
        .map(|index| format!("fn unused_{index}() {{}}\n"))
        .collect();
    let fixture = rust_fixture(
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"loud\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"loud\"\nversion = \"0.1.0\"\n",
            ),
            ("src/lib.rs", &many),
        ],
        "module-rust-loud",
        300,
    );
    let mut pages = Vec::new();
    for env in [IN_PROCESS, MODULE] {
        let daemon = Daemon::start(&fixture, &[env]).await;
        let mut session = Session::start(&fixture).await;
        let page = problems(&mut session, &fixture, Duration::from_secs(180), |text| {
            text.starts_with("rust: ready")
        })
        .await;
        assert!(
            page.starts_with("rust: ready; errors: 0; warnings: 4000"),
            "{page}"
        );
        pages.push(page);
        session.close(&fixture).await;
        drop(daemon);
    }
    parity::assert_parity(&pages[..1], &pages[1..]);
}

/// Killing the Rust module while rust-analyzer indexes settles the waiting semantic call with a
/// typed `module_unavailable (bundled.rust:…)` refusal; the daemon is the same process and still
/// healthy, an unrelated language answers on it, rust-analyzer dies with its module, the next
/// Rust call starts a fresh module, and nothing survives the daemon.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn killing_the_module_while_rust_analyzer_indexes_is_typed_and_leaves_no_orphan() {
    // No project check: the only typed fault in the reply is the analyzer's own.
    let fixture = Fixture::new(PARITY_FILES, providers("module-rust-kill"));
    let mut daemon = Daemon::start(&fixture, &[MODULE]).await;
    let daemon_pid = daemon.pid();
    let mut session = Session::start(&fixture).await;
    let call = json!({"symbol":"src/lib.rs#Service/work"});
    // The semantic call starts the module and rust-analyzer; it cannot answer before the
    // analyzer has loaded the workspace.
    let (fixture, outcome) = {
        let pending = tokio::spawn(async move {
            let reply = session.call(&fixture, "ide.symbol", call).await;
            (session, fixture, reply)
        });
        let deadline = Instant::now() + Duration::from_secs(30);
        let (module, server) = loop {
            if let Some(found) = analyzer(&daemon.tree()) {
                break found;
            }
            assert!(Instant::now() < deadline, "rust-analyzer never started");
            tokio::time::sleep(Duration::from_millis(20)).await;
        };
        // Indexing: rust-analyzer runs, loading the workspace, and the call is still waiting.
        tokio::time::sleep(Duration::from_millis(300)).await;
        assert!(server.exists(), "rust-analyzer is loading");
        assert!(
            !pending.is_finished(),
            "the semantic call waits for indexing"
        );
        let loading: Vec<ProcessIdentity> = descendants(module.id.pid)
            .into_iter()
            .map(|(id, _)| id)
            .collect();
        // SAFETY: `module` is the exact identity captured as this test's daemon child just now.
        unsafe { libc::kill(module.id.pid, libc::SIGKILL) };
        let (returned, fixture, reply) = pending.await.unwrap();
        session = returned;
        assert!(module.id.gone().await, "the killed module is reaped");
        for id in loading {
            assert!(id.gone().await, "{id:?} outlived its module");
        }
        (fixture, reply)
    };
    let text = outcome["text"].as_str().unwrap_or_default();
    // The symbol card keeps its definition and names why usages are missing, or the call fails
    // whole; either way its own text names the analyzer module's typed fault.
    assert!(
        outcome["code"] == "provider_unavailable" || text.contains("usages: unavailable"),
        "the original call fails its semantic part: {outcome}"
    );
    assert!(
        text.contains("module_unavailable (bundled.rust:"),
        "the original call names the module fault: {outcome}"
    );
    assert_eq!(daemon.pid(), daemon_pid, "the daemon is the same process");
    assert!(
        std::os::unix::net::UnixStream::connect(fixture.runtime.join("agent-ide.sock")).is_ok(),
        "the daemon still serves"
    );
    let unrelated = session
        .call(&fixture, "ide.outline", json!({"path":"style.css"}))
        .await;
    assert_eq!(unrelated["kind"], "outline", "{unrelated}");
    assert!(
        unrelated["text"]
            .as_str()
            .unwrap_or_default()
            .contains(".button")
    );
    // The next Rust demand starts a fresh module and answers.
    let restarted = session
        .call(&fixture, "ide.outline", json!({"path":"src/lib.rs"}))
        .await;
    assert_eq!(restarted["kind"], "outline", "{restarted}");
    let tree = daemon.tree();
    let owned = tree.all();
    session.close(&fixture).await;
    drop(daemon);
    for id in owned {
        assert!(id.gone().await, "{id:?} survived the daemon");
    }
}

/// A `cargo check` whose build script never finishes, with project checks enabled and a 10 s
/// ceiling: cargo and the build script demonstrably run, the check ends as `check timed out`
/// (never clean, never a hang), every check process is reaped, and the daemon is the same.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn a_stalled_cargo_check_times_out_and_leaves_no_orphan() {
    let fixture = rust_fixture(
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"stalled\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"stalled\"\nversion = \"0.1.0\"\n",
            ),
            (
                "build.rs",
                "fn main() { std::thread::sleep(std::time::Duration::from_secs(600)); }\n",
            ),
            ("src/lib.rs", "pub fn one() -> u8 { 1 }\n"),
        ],
        "module-rust-stall",
        10,
    );
    let mut daemon = Daemon::start(&fixture, &[MODULE]).await;
    let daemon_pid = daemon.pid();
    let mut session = Session::start(&fixture).await;
    let checking = session
        .call(
            &fixture,
            "ide.context",
            json!({"kind":"problems","language":"rust"}),
        )
        .await;
    assert!(
        checking["text"]
            .as_str()
            .is_some_and(|text| text.starts_with("rust: checking")),
        "the check runs: {checking}"
    );
    // cargo and the stalled build script run as the daemon's confined check.
    let deadline = Instant::now() + Duration::from_secs(60);
    let running = loop {
        let all = descendants(daemon_pid);
        if all
            .iter()
            .any(|(_, command)| command.contains("build-script-build"))
        {
            break all;
        }
        assert!(
            Instant::now() < deadline,
            "the build script never ran: {all:?}"
        );
        tokio::time::sleep(Duration::from_millis(100)).await;
    };
    assert!(
        running
            .iter()
            .any(|(_, command)| command.contains("/bin/cargo check")),
        "cargo runs: {running:?}"
    );
    let check: Vec<ProcessIdentity> = running
        .iter()
        .filter(|(_, command)| {
            command.contains("cargo")
                || command.contains("build-script")
                || command.contains("rustc")
        })
        .map(|(id, _)| *id)
        .collect();
    let page = problems(&mut session, &fixture, Duration::from_secs(60), |text| {
        text.starts_with("rust: check timed out")
    })
    .await;
    assert!(page.starts_with("rust: check timed out"), "{page}");
    for id in check {
        assert!(id.gone().await, "{id:?} outlived its timed-out check");
    }
    assert_eq!(daemon.pid(), daemon_pid, "the daemon is the same process");
    let owned = daemon.tree().all();
    session.close(&fixture).await;
    drop(daemon);
    for id in owned {
        assert!(id.gone().await, "{id:?} survived the daemon");
    }
}

/// The fixed offsets the transcript asks about point at the names they mean.
#[test]
fn offsets_point_at_their_names() {
    let (_, lib) = PARITY_FILES
        .iter()
        .find(|(path, _)| *path == "src/lib.rs")
        .unwrap();
    assert!(lib[WORK_OFFSET..].starts_with("work(&self)"));
    assert!(lib[HELPER_CALL_OFFSET..].starts_with("helper()\n"));
}

/// The resident memory of `id` in KiB, 0 once it is gone.
fn rss_kib(id: ProcessIdentity) -> u64 {
    let listing = std::process::Command::new("/bin/ps")
        .args(["-o", "rss=", "-p", &id.pid.to_string()])
        .output()
        .unwrap();
    String::from_utf8_lossy(&listing.stdout)
        .trim()
        .parse()
        .unwrap_or(0)
}

/// Milliseconds of one settled call that must answer `kind`.
async fn timed(
    session: &mut Session,
    fixture: &Fixture,
    tool: &str,
    arguments: Value,
    kind: &str,
) -> f64 {
    let started = Instant::now();
    let reply = session.call(fixture, tool, arguments).await;
    let elapsed = started.elapsed().as_secs_f64() * 1000.0;
    assert_eq!(reply["kind"], kind, "{reply}");
    elapsed
}

/// A measurement, not a contract (design §3.2.4): for the in-process path and the module it
/// records cold first outlines (a fresh session each), warm `ide.outline` and `ide.symbol`
/// latencies once rust-analyzer is ready, and the resident memory of the daemon's process tree,
/// written as JSON to `AGENT_IDE_MODULE_MEASURE_OUT`. Without that variable it measures nothing.
#[tokio::test]
#[ignore = "measurement; requires the accepted Rust inputs and AGENT_IDE_MODULE_MEASURE_OUT"]
async fn rust_module_measure() {
    let Some(out) = std::env::var_os("AGENT_IDE_MODULE_MEASURE_OUT").map(std::path::PathBuf::from)
    else {
        eprintln!("rust_module_measure skipped: AGENT_IDE_MODULE_MEASURE_OUT is not set");
        return;
    };
    let fixture = rust_fixture(PARITY_FILES, "module-rust-measure", 300);
    let (cold_runs, warmup, samples) = (15, 20, 200);
    let mut report = serde_json::Map::new();
    for (mode, env) in [("in_process", IN_PROCESS), ("module", MODULE)] {
        let mut daemon = Daemon::start(&fixture, &[env]).await;
        let outline = json!({"path":"src/lib.rs"});
        let symbol = json!({"symbol":"src/lib.rs#Service/work"});
        let mut cold = Vec::new();
        let mut session = Session::start(&fixture).await;
        for run in 0..cold_runs {
            if run > 0 {
                session.close(&fixture).await;
                session = Session::start(&fixture).await;
            }
            cold.push(
                timed(
                    &mut session,
                    &fixture,
                    "ide.outline",
                    outline.clone(),
                    "outline",
                )
                .await,
            );
        }
        ready(&mut session, &fixture).await;
        let mut measured = serde_json::Map::new();
        measured.insert("cold_outline_ms".into(), json!(cold));
        for (name, tool, arguments, kind) in [
            ("warm_outline_ms", "ide.outline", outline.clone(), "outline"),
            ("warm_symbol_ms", "ide.symbol", symbol.clone(), "symbol"),
        ] {
            for _ in 0..warmup {
                timed(&mut session, &fixture, tool, arguments.clone(), kind).await;
            }
            let mut values = Vec::new();
            for _ in 0..samples {
                values.push(timed(&mut session, &fixture, tool, arguments.clone(), kind).await);
            }
            measured.insert(name.into(), json!(values));
        }
        let tree = daemon.tree();
        let mut memory = vec![
            json!({"process":"daemon","rss_kib":rss_kib(ProcessIdentity::of(daemon.pid()).unwrap().0)}),
        ];
        for node in &tree.children {
            memory.push(json!({"process":node.command,"rss_kib":rss_kib(node.id)}));
            for (id, command) in &node.children {
                memory.push(json!({"process":format!("  {command}"),"rss_kib":rss_kib(*id)}));
            }
        }
        measured.insert("rss".into(), json!(memory));
        report.insert(mode.into(), Value::Object(measured));
        session.close(&fixture).await;
        drop(daemon);
    }
    report.insert(
        "method".into(),
        json!({"cold_runs": cold_runs, "warmup": warmup, "calls": samples,
               "clock": "wall time of one settled MCP tools/call round trip measured in the test process"}),
    );
    std::fs::write(
        &out,
        serde_json::to_vec_pretty(&Value::Object(report)).unwrap(),
    )
    .unwrap();
}

/// The module fault seam (`agent_ide_core::modules::serve::FAULT_SEAM`).
const FAULT_SEAM: &str = "AGENT_IDE_TEST_MODULE_FAULT";
/// The module request budget seam (`agent_ide_core::modules::router::BUDGET_SEAM`).
const BUDGET_SEAM: &str = "AGENT_IDE_TEST_MODULE_BUDGET_MS";

/// The M-A conformance cases on the Rust analyzer module with the real rust-analyzer: once the
/// analyzer is ready, a stall past the module budget and a malformed reply each settle the next
/// semantic call with a typed `module_unavailable (bundled.rust:…)` (timeout, malformed) on the
/// same healthy daemon, and the following call starts a fresh module that answers semantically;
/// neither the failed module nor its rust-analyzer survives.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_analyzer_seam_faults_are_typed_and_restart() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-seams", 300);
    let usages = json!({"symbol":"src/lib.rs#Service/work"});
    for (fault, cause) in [("stall", "timeout"), ("malformed", "malformed")] {
        // The flag is created only once the analyzer is ready, so the seam fires on the next
        // semantic request rather than on the warm-up.
        let flag = fixture.base.join(format!("rust-module-fault-{fault}"));
        let seam = format!("{fault}:semantic:{}", flag.display());
        let mut daemon = Daemon::start(
            &fixture,
            &[MODULE, (FAULT_SEAM, &seam), (BUDGET_SEAM, "5000")],
        )
        .await;
        let daemon_pid = daemon.pid();
        let mut session = Session::start(&fixture).await;
        ready(&mut session, &fixture).await;
        let (first, server) = analyzer(&daemon.tree()).expect("the analyzer module runs");
        std::fs::write(&flag, "").unwrap();
        let started = Instant::now();
        let failed = session.call(&fixture, "ide.symbol", usages.clone()).await;
        let failed_after = started.elapsed();
        assert!(!flag.exists(), "{fault}: the seam fired");
        assert!(
            failed
                .to_string()
                .contains("module_unavailable (bundled.rust:")
                && failed.to_string().contains(cause),
            "{fault}: the call names the typed module fault: {failed}"
        );
        assert!(
            failed_after < Duration::from_secs(30),
            "{fault} answered after {failed_after:?}"
        );
        // The next demands retire the failed instance (reaping it and its rust-analyzer) and
        // start a fresh one.
        ready(&mut session, &fixture).await;
        assert!(first.id.gone().await, "{fault}: the failed module survived");
        assert!(server.gone().await, "{fault}: its rust-analyzer survived");
        let (second, _) = analyzer(&daemon.tree()).expect("a fresh analyzer module runs");
        assert_ne!(
            first.id, second.id,
            "{fault}: the failed module was replaced"
        );
        assert_eq!(daemon.pid(), daemon_pid, "{fault}: same daemon");
        let owned = daemon.tree().all();
        session.close(&fixture).await;
        drop(daemon);
        for id in owned {
            assert!(id.gone().await, "{fault}: {id:?} survived the daemon");
        }
    }
}

/// The M-A conformance cases on the Rust checker module: a stall past the budget, a malformed
/// reply and a `kill -9` of the checker module each leave Rust's check `check failed` naming
/// `module_unavailable (bundled.rust:…)`, never clean; after an edit the next check starts a
/// fresh module and lands, on the same daemon.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_checker_seam_faults_are_typed_and_restart() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-check-seams", 30);
    for (fault, expected) in [
        ("stall", "module_unavailable (bundled.rust:request:timeout)"),
        (
            "malformed",
            "module_unavailable (bundled.rust:request:malformed)",
        ),
        ("kill", "module_unavailable (bundled.rust:request:exited)"),
    ] {
        let flag = fixture.base.join(format!("rust-check-fault-{fault}"));
        std::fs::write(&flag, "").unwrap();
        let kind = if fault == "malformed" {
            "malformed"
        } else {
            "stall"
        };
        let seam = format!("{kind}:check_plan:{}", flag.display());
        let mut daemon = Daemon::start(
            &fixture,
            &[MODULE, (FAULT_SEAM, &seam), (BUDGET_SEAM, "3000")],
        )
        .await;
        let daemon_pid = daemon.pid();
        let mut session = Session::start(&fixture).await;
        if fault == "kill" {
            let deadline = Instant::now() + Duration::from_secs(30);
            let checker = loop {
                if let Some(node) = daemon.tree().module("rust", "checker").cloned()
                    && !flag.exists()
                {
                    break node;
                }
                assert!(Instant::now() < deadline, "the stalled checker never ran");
                tokio::time::sleep(Duration::from_millis(50)).await;
            };
            // SAFETY: the exact module identity captured as this test's daemon child just now.
            unsafe { libc::kill(checker.id.pid, libc::SIGKILL) };
        }
        let failed = problems(&mut session, &fixture, Duration::from_secs(60), |text| {
            text.contains(expected)
        })
        .await;
        assert!(
            failed.starts_with("rust: check failed") && failed.contains(expected),
            "{fault}: the check names the fault:\n{failed}"
        );
        std::fs::write(
            fixture.root.join("src/lib.rs"),
            format!("pub fn edited_{fault}() -> u8 {{\n    1\n}}\n"),
        )
        .unwrap();
        let landed = problems(&mut session, &fixture, Duration::from_secs(120), |text| {
            text.starts_with("rust: ready")
        })
        .await;
        assert!(
            landed.starts_with("rust: ready"),
            "{fault}: the next check lands:\n{landed}"
        );
        assert_eq!(daemon.pid(), daemon_pid, "{fault}: same daemon");
        session.close(&fixture).await;
        drop(daemon);
        fixture.git(&["checkout", "--quiet", "--", "."]);
    }
}

/// The Rust analyzer module shares the supervised slots' restart policy: after the initial
/// start and three restarts within the window (each death settled typed on the next demand),
/// a further demand is refused `restart_exhausted` (typed, on the same daemon) and no fifth
/// module starts.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn rust_analyzer_crash_loop_exhausts_the_restart_budget() {
    let fixture = rust_fixture(PARITY_FILES, "module-rust-crash-loop", 300);
    let mut daemon = Daemon::start(&fixture, &[MODULE]).await;
    let daemon_pid = daemon.pid();
    let mut session = Session::start(&fixture).await;
    let outline = json!({"path":"src/lib.rs"});
    let context = json!({"path":"src/lib.rs","byte_offset":WORK_OFFSET});
    // Deaths are noticed through the backend's own path (context) and through the core's
    // semantic paths (symbol, graph); each counts once against the same budget.
    let demands = [
        ("ide.context", context.clone()),
        ("ide.symbol", json!({"symbol":"src/lib.rs#Service/work"})),
        ("ide.graph", json!({"symbol":"src/lib.rs#user"})),
        ("ide.symbol", json!({"symbol":"src/lib.rs#user"})),
    ];
    for attempt in 0..4 {
        // A demand starts the module (the first after a death is settled with its fault).
        let (tool, arguments) = &demands[attempt];
        let deadline = Instant::now() + Duration::from_secs(30);
        let module = loop {
            let _ = session.call(&fixture, tool, arguments.clone()).await;
            if let Some((module, _)) = analyzer(&daemon.tree()) {
                break module;
            }
            assert!(
                Instant::now() < deadline,
                "attempt {attempt}: no analyzer module"
            );
        };
        // SAFETY: the exact module identity captured as a child of this test's daemon.
        unsafe { libc::kill(module.id.pid, libc::SIGKILL) };
        assert!(module.id.gone().await);
        // Let each backoff (250 ms, 1 s, 4 s) pass so the next start really happens.
        tokio::time::sleep(Duration::from_millis([300, 1100, 4100, 0][attempt])).await;
    }
    // The symbol card names a module's typed failure (context answers lexically instead).
    let usages = json!({"symbol":"src/lib.rs#Service/work"});
    let mut refused = Value::Null;
    for _ in 0..3 {
        refused = session.call(&fixture, "ide.symbol", usages.clone()).await;
        if refused.to_string().contains("restart_exhausted") {
            break;
        }
    }
    assert!(
        refused.to_string().contains("restart_exhausted"),
        "a demand names the exhausted budget: {refused}"
    );
    assert!(
        analyzer(&daemon.tree()).is_none(),
        "no fifth module started"
    );
    let lexical = session.call(&fixture, "ide.outline", outline).await;
    assert_eq!(
        lexical["kind"], "outline",
        "outline still answers from source: {lexical}"
    );
    assert_eq!(daemon.pid(), daemon_pid, "same daemon");
    session.close(&fixture).await;
}

/// `text` with each opaque reference a reply names in prose (`source_ref <64 hex>-<n>`, also
/// `detail_ref …`, whatever punctuation follows) written as `<ref>`; other hex runs stay.
fn mask_text_refs(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    loop {
        let next = ["source_ref ", "detail_ref "]
            .iter()
            .filter_map(|marker| rest.find(marker).map(|at| (at, marker.len())))
            .min();
        let Some((at, marker)) = next else {
            out.push_str(rest);
            return out;
        };
        out.push_str(&rest[..at + marker]);
        rest = &rest[at + marker..];
        let hex = rest.bytes().take_while(u8::is_ascii_hexdigit).count();
        if hex == 64 {
            let suffix = rest[hex..].strip_prefix('-').map_or(0, |tail| {
                1 + tail.bytes().take_while(u8::is_ascii_digit).count()
            });
            out.push_str("<ref>");
            rest = &rest[hex + suffix..];
        }
    }
}

/// `text` with the per-daemon observation counters of a context reply masked (`source_sequence:`
/// and `document_version:`): they count every observation of the run, and the readiness wait
/// polls a variable number of times. Everything else stays byte-compared.
fn mask_counters(text: &str) -> String {
    text.split('\n')
        .map(|line| {
            if line.starts_with("source_sequence: ") {
                "source_sequence: <n>".to_owned()
            } else if line.starts_with("document_version: Some(") {
                "document_version: Some(<n>)".to_owned()
            } else {
                line.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Only the elapsed slot of test result lines is masked; budgets and other text stay.
#[test]
fn seconds_are_masked_and_nothing_else() {
    assert_eq!(
        mask_seconds("tests #2: 1 passed, 1 failed, 3 s\ntests #3: no summary parsed, 12 s"),
        "tests #2: 1 passed, 1 failed, <seconds> s\ntests #3: no summary parsed, <seconds> s"
    );
    for kept in [
        "tests #1: started — cargo test --lib (budget 120 s); poll: call ide.test",
        "tests #1: stopped at budget 120 s — 1 passed, 0 failed so far",
        "a line, 3 s that is not a test result",
    ] {
        assert_eq!(mask_seconds(kept), kept);
    }
    assert_ne!(
        mask_seconds("tests #1: started — cargo test (budget 120 s)"),
        mask_seconds("tests #1: started — cargo test (budget 60 s)"),
        "two budgets stay different"
    );
}

/// The shipping binary's `module rust analyzer` process, spawned like the daemon spawns it
/// (cleared environment plus the Rust module environment, the worktree as working directory),
/// starts the pinned rust-analyzer within `hello` and answers readiness: the daemon↔module path
/// without the daemon, so it runs without sockets.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn the_module_process_starts_rust_analyzer_within_hello() {
    use agent_ide_core::modules::{
        contract::{Capability, ModuleId, Outcome, Readiness, Role},
        host::{Call, HostChannel, NoEffects},
        payload::{SemanticQuery, decode, encode},
        provider::ProviderGrant,
    };
    let fixture = Fixture::new(PARITY_FILES, providers("module-rust-process"));
    let dir = std::path::PathBuf::from(input("AGENT_IDE_RUST_TOOLCHAIN_DIR"));
    let namespace = fixture.base.join("namespace");
    for sub in ["cargo", "target", "tmp"] {
        std::fs::create_dir_all(namespace.join(sub)).unwrap();
    }
    let settings = agent_ide_lang_rust::module::RustProviderSettings {
        binary: input("AGENT_IDE_RUST_ANALYZER").into(),
        version: "rust-analyzer 1.98.1 (48a229ce 2026-09-01)".into(),
        cargo: dir.join("bin/cargo"),
        cargo_home: None,
        cargo_version: "cargo 1.98.1".into(),
        rustc: dir.join("bin/rustc"),
        rustc_version: "rustc 1.98.1".into(),
        toolchain: input("AGENT_IDE_RUST_TOOLCHAIN"),
        trust: "fixture-disabled".into(),
        cache_namespace: namespace.display().to_string(),
    };
    let home = agent_ide_core::userhome::user_home();
    let digest = |path: &std::path::Path| {
        blake3::hash(&std::fs::read(path).unwrap())
            .to_hex()
            .to_string()
    };
    let mut env: Vec<(String, String)> = agent_ide_lang_rust::module::MODULE_ENV
        .iter()
        .filter_map(|name| Some(((*name).to_owned(), std::env::var(name).ok()?)))
        .collect();
    env.sort();
    let mut child = tokio::process::Command::new(parity::binary())
        .args(["module", "rust", "analyzer"])
        .env_clear()
        .envs(env)
        .current_dir(&fixture.root)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::inherit())
        .kill_on_drop(true)
        .spawn()
        .unwrap();
    let offer = agent_ide_core::modules::contract::HelloOffer {
        config: agent_ide_core::modules::contract::ModuleConfig {
            worktree: Some(fixture.root.clone()),
            provider: Some(json!({
                "grant": ProviderGrant {
                    accepted: [&settings.binary, &settings.cargo, &settings.rustc]
                        .into_iter()
                        .map(|path| (path.clone(), digest(path)))
                        .collect(),
                    request_timeout_ms: 30_000,
                    roots: [namespace.clone()]
                        .into_iter()
                        .chain(home.clone())
                        .chain(["/usr/bin", "/bin"].map(std::path::PathBuf::from))
                        .collect(),
                },
                "settings": settings,
            })),
            checks: None,
            env: Default::default(),
            home,
        },
        ..agent_ide_core::modules::fake::offer(
            ModuleId::bundled("rust"),
            env!("CARGO_PKG_VERSION"),
            Role::Analyzer,
            1,
        )
    };
    let started = Instant::now();
    let opened = HostChannel::open(
        child.stdout.take().unwrap(),
        child.stdin.take().unwrap(),
        offer,
        Duration::from_secs(120),
    )
    .await;
    let (mut channel, _) = opened.unwrap_or_else(|failure| panic!("hello: {failure}"));
    eprintln!("hello answered after {:?}", started.elapsed());
    let deadline = Instant::now() + Duration::from_secs(120);
    loop {
        let reply = channel
            .call(
                Call {
                    capability: Capability::Semantic,
                    scope_key: "scope".into(),
                    revision_key: "revision".into(),
                    payload: encode(&SemanticQuery::Readiness {}),
                    attachments: Vec::new(),
                },
                Duration::from_secs(5),
                &mut NoEffects,
            )
            .await
            .unwrap();
        let readiness: Readiness = match reply.outcome {
            Outcome::Result(value) => decode(value).unwrap(),
            Outcome::Error(error) => panic!("readiness: {error:?}"),
        };
        eprintln!("readiness after {:?}: {readiness:?}", started.elapsed());
        if readiness == Readiness::Ready {
            break;
        }
        assert_ne!(
            readiness,
            Readiness::Degraded,
            "the workspace failed to load"
        );
        assert!(Instant::now() < deadline, "never ready");
    }
    // A symbol context answers like the in-process exchange: no wait for diagnostics a
    // byte-offset query never asked for, well inside the core's module call budget.
    let (_, lib) = PARITY_FILES
        .iter()
        .find(|(path, _)| *path == "src/lib.rs")
        .unwrap();
    let asked = Instant::now();
    let reply = channel
        .call(
            Call {
                capability: Capability::Semantic,
                scope_key: "scope".into(),
                revision_key: "revision".into(),
                payload: encode(&SemanticQuery::Context {
                    source: agent_ide_core::modules::payload::SourceRef {
                        path: "src/lib.rs".into(),
                        revision: "r1".into(),
                        text: agent_ide_core::modules::payload::SourceText::Inline(
                            (*lib).to_owned(),
                        ),
                    },
                    byte_offset: Some(HELPER_CALL_OFFSET as u64),
                }),
                attachments: Vec::new(),
            },
            Duration::from_secs(30),
            &mut NoEffects,
        )
        .await
        .unwrap();
    eprintln!("symbol context after {:?}", asked.elapsed());
    assert!(matches!(reply.outcome, Outcome::Result(_)), "{reply:?}");
    assert!(
        asked.elapsed() < Duration::from_secs(5),
        "a symbol context waited {:?}",
        asked.elapsed()
    );
}

/// Opaque references are masked wherever a structured reply carries them; nulls and other
/// values (hashes in business fields included) stay.
#[test]
fn references_are_masked_and_nothing_else() {
    let mut reply = json!({"result":{"source_ref":"a".repeat(64) + "-2","outcome":"replaced",
        "digest":"b".repeat(64)},"detail_ref":null,"items":[{"detail_ref":"c-1"}]});
    mask_refs(&mut reply);
    let mut arguments = json!({"op":"replace","source_ref":"d".repeat(64) + "-7","lines":"2-2"});
    mask_refs(&mut arguments);
    assert_eq!(
        arguments,
        json!({"op":"replace","source_ref":"<ref>","lines":"2-2"})
    );
    assert_eq!(
        reply,
        json!({"result":{"source_ref":"<ref>","outcome":"replaced","digest":"b".repeat(64)},
            "detail_ref":null,"items":[{"detail_ref":"<ref>"}]})
    );
}

/// The daemon's own open path for a Rust analyzer module, without the daemon: the pinned
/// shipping binary started by `analyzer_command` (the module environment the root declares),
/// `analyzer_offer` with the backend's grant and settings, `open_session` with the static Rust
/// session shape, then the session's readiness barrier across the boundary until ready.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_RUST_TOOLCHAIN_DIR, AGENT_IDE_RUST_ANALYZER and AGENT_IDE_RUST_TOOLCHAIN inputs"]
async fn the_daemon_open_path_reaches_a_ready_rust_analyzer() {
    use agent_ide_core::{
        intelligence::{freshness::ViewGeneration, session::ProviderSettings},
        modules::{analyzer, launch::ModuleExecutable},
        workspace::authority::WorktreeRef,
    };
    agent_ide::languages::install();
    let fixture = Fixture::new(PARITY_FILES, providers("module-rust-open"));
    let dir = std::path::PathBuf::from(input("AGENT_IDE_RUST_TOOLCHAIN_DIR"));
    let namespace = fixture.base.join("namespace");
    for sub in ["cargo", "target", "tmp"] {
        std::fs::create_dir_all(namespace.join(sub)).unwrap();
    }
    let settings = agent_ide_lang_rust::module::RustProviderSettings {
        binary: input("AGENT_IDE_RUST_ANALYZER").into(),
        version: "rust-analyzer 1.98.1 (48a229ce 2026-09-01)".into(),
        cargo: dir.join("bin/cargo"),
        cargo_home: None,
        cargo_version: "cargo 1.98.1".into(),
        rustc: dir.join("bin/rustc"),
        rustc_version: "rustc 1.98.1".into(),
        toolchain: input("AGENT_IDE_RUST_TOOLCHAIN"),
        trust: "fixture-disabled".into(),
        cache_namespace: namespace.display().to_string(),
    };
    let digest = |path: &std::path::Path| {
        blake3::hash(&std::fs::read(path).unwrap())
            .to_hex()
            .to_string()
    };
    let executable = ModuleExecutable::pin(&parity::binary()).expect("a pinned module binary");
    let worktree = WorktreeRef::from_discovery(
        fixture.root.clone(),
        fixture.root.clone(),
        fixture.root.join(".git"),
        1,
    )
    .unwrap();
    let command = analyzer::analyzer_command(&executable, "rust", &worktree).expect("a command");
    let mut child = agent_ide_core::execution::spawn_granted_provider(&command).unwrap();
    let offer = analyzer::analyzer_offer(
        &executable,
        "rust",
        1,
        &worktree,
        [&settings.binary, &settings.cargo, &settings.rustc]
            .into_iter()
            .map(|path| (path.clone(), digest(path)))
            .collect(),
        [namespace.clone()]
            .into_iter()
            .chain(agent_ide_core::userhome::user_home())
            .chain(["/usr/bin", "/bin"].map(std::path::PathBuf::from))
            .collect(),
        Duration::from_secs(30),
        serde_json::to_value(&settings).unwrap(),
    );
    let generation = ViewGeneration {
        backend: 1,
        configuration: 1,
        toolchain: 1,
        view: 1,
    };
    let started = Instant::now();
    let mut live = analyzer::open_session(
        child.stdout.take().unwrap(),
        child.stdin.take().unwrap(),
        offer,
        worktree,
        1,
        generation,
        ProviderSettings::new(agent_ide_lang_rust::profile::RustModuleSession),
        Duration::from_secs(30),
    )
    .await
    .unwrap_or_else(|error| panic!("open: {error}"));
    eprintln!("open after {:?}", started.elapsed());
    let deadline = Instant::now() + Duration::from_secs(120);
    loop {
        match live.wait_ready(Duration::from_millis(100)).await {
            Ok(()) => break,
            Err(error) => {
                // A warming provider is loading, never a gone transport.
                assert!(
                    !matches!(
                        error,
                        agent_ide_core::intelligence::session::ReadinessError::Gone
                    ),
                    "a live module answered its readiness as gone: alive {} fault {:?}",
                    live.is_alive(),
                    live.module_unavailable()
                );
                assert!(
                    Instant::now() < deadline,
                    "never ready: {error:?}; fault {:?}",
                    live.module_unavailable()
                );
                eprintln!(
                    "readiness after {:?}: {error:?} alive {} fault {:?} remote {:?}",
                    started.elapsed(),
                    live.is_alive(),
                    live.module_unavailable(),
                    live.remote_fault()
                );
                tokio::time::sleep(Duration::from_millis(300)).await;
            }
        }
    }
    eprintln!("ready after {:?}", started.elapsed());
    let _ = child.kill().await;
}

/// A language server that completes the handshake as the accepted rust-analyzer, reports itself
/// quiescent and fails every documentSymbols and references request (copied from the product
/// suite's in-process control).
const EXCHANGE_STUB_SERVER: &str = r#"
const send = (message) => {
  const text = JSON.stringify(message);
  process.stdout.write(`Content-Length: ${Buffer.byteLength(text)}\r\n\r\n${text}`);
};
const reply = (id, result) => send({ jsonrpc: '2.0', id, result });
const fail = (id) => send({ jsonrpc: '2.0', id, error: { code: -32603, message: 'fixture exchange failure' } });
let buffer = Buffer.alloc(0);
process.stdin.on('data', (chunk) => {
  buffer = Buffer.concat([buffer, chunk]);
  for (;;) {
    const header = buffer.indexOf('\r\n\r\n');
    if (header < 0) return;
    const length = parseInt(buffer.slice(0, header).toString().match(/Content-Length: (\d+)/)?.[1] ?? '0', 10);
    if (buffer.length < header + 4 + length) return;
    const message = JSON.parse(buffer.slice(header + 4, header + 4 + length).toString());
    buffer = buffer.slice(header + 4 + length);
    switch (message.method) {
      case 'initialize':
        reply(message.id, {
          capabilities: {
            textDocumentSync: 1,
            documentSymbolProvider: true,
            hoverProvider: true,
            referencesProvider: true,
          },
          serverInfo: { name: 'rust-analyzer', version: '1.98.1 (48a229ce 2026-09-01)' },
        });
        break;
      case 'shutdown':
        reply(message.id, null);
        break;
      case 'exit':
        process.exit(0);
      case 'textDocument/documentSymbol':
      case 'textDocument/references':
        fail(message.id);
        break;
      default:
        if (message.id !== undefined) reply(message.id, null);
    }
  }
});
const report = () => {
  send({ jsonrpc: '2.0', method: 'experimental/serverStatus', params: { health: 'ok', quiescent: true } });
  setTimeout(report, 100);
};
report();
"#;

/// The module-mode twin of the in-process `configured_product_failed_exchange_rust_outline_
/// answers_from_source` (pinned in process): a provider that is ready but fails documentSymbols
/// and references. The outline and a symbol read answer from the exact source outline with the
/// module's typed cause in the footer, a file the source scanner refuses keeps its refusal, and
/// the symbol card's live sections name the typed `rust: module_unavailable (bundled.rust:…)`.
#[tokio::test]
#[ignore = "requires the accepted AGENT_IDE_NODE and AGENT_IDE_RUST_TOOLCHAIN_DIR inputs"]
async fn a_failed_provider_exchange_answers_from_source_with_typed_attribution() {
    use std::os::unix::fs::PermissionsExt;
    let base = std::env::temp_dir()
        .canonicalize()
        .unwrap()
        .join(format!("exchange-stub-{}", std::process::id()));
    std::fs::create_dir_all(&base).unwrap();
    let stub = base.join("exchange-stub-server.mjs");
    std::fs::write(&stub, EXCHANGE_STUB_SERVER).unwrap();
    let wrapper = base.join("exchange-rust-provider");
    std::fs::write(
        &wrapper,
        format!(
            "#!/bin/sh\nexec '{}' '{}'\n",
            input("AGENT_IDE_NODE"),
            stub.display()
        ),
    )
    .unwrap();
    std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o700)).unwrap();
    let dir = input("AGENT_IDE_RUST_TOOLCHAIN_DIR");
    let fixture = Fixture::new(
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"exchange\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
            ),
            (
                "src/lib.rs",
                "/// Answers broken.\npub fn value() -> i32 { 7 }\n\npub fn caller() -> i32 { value() }\n",
            ),
            (
                "src/refused.rs",
                "// attached to the item below\npub fn refused() {}\n",
            ),
        ],
        json!([{
            "executable":accepted(wrapper.to_str().unwrap(),"rust-analyzer 1.98.1 (48a229ce 2026-09-01)"),
            "settings":"rust_cache_priming_disabled_v1",
            "toolchain":"1.98.1-aarch64-apple-darwin",
            "cargo":accepted(&format!("{dir}/bin/cargo"),"cargo 1.98.1"),
            "cargo_version":"cargo 1.98.1",
            "rustc":accepted(&format!("{dir}/bin/rustc"),"rustc 1.98.1"),
            "rustc_version":"rustc 1.98.1",
            "trust":"fixture-disabled",
            "cache_namespace":"module-rust-exchange"
        }]),
    );
    let daemon = Daemon::start(&fixture, &[MODULE]).await;
    let mut session = Session::start(&fixture).await;
    let deadline = Instant::now() + Duration::from_secs(60);
    let outline = loop {
        let reply = session
            .call(&fixture, "ide.outline", json!({"path":"src/lib.rs"}))
            .await;
        if reply["kind"] == "outline"
            && !reply["text"]
                .as_str()
                .unwrap_or_default()
                .contains("still indexing")
        {
            break reply;
        }
        assert!(
            Instant::now() < deadline,
            "the outline never settled: {reply}"
        );
        tokio::time::sleep(Duration::from_millis(250)).await;
    };
    let text = outline["text"].as_str().unwrap_or_default();
    assert!(text.contains("pub fn value() -> i32"), "{outline}");
    assert!(
        text.contains("outline: from source, exact (")
            && text.contains("module_unavailable (bundled.rust:"),
        "the exchange-failed outline answers from source with the typed cause: {outline}"
    );
    let read = session
        .call(&fixture, "ide.read", json!({"symbol":"src/lib.rs#value"}))
        .await;
    let read_text = read["text"].as_str().unwrap_or_default();
    assert!(read_text.contains("pub fn value()"), "{read}");
    assert!(
        read_text.contains("outline: from source, exact ("),
        "{read}"
    );
    let refused = session
        .call(&fixture, "ide.outline", json!({"path":"src/refused.rs"}))
        .await;
    assert_eq!(refused["code"], "provider_unavailable", "{refused}");
    let symbol = session
        .call(&fixture, "ide.symbol", json!({"symbol":"src/lib.rs#value"}))
        .await;
    let card = symbol["text"].as_str().unwrap_or_default();
    assert_eq!(symbol["kind"], "symbol", "{symbol}");
    assert!(
        card.contains("signature: pub fn value() -> i32"),
        "{symbol}"
    );
    assert!(
        card.contains("usages: unavailable (rust: module_unavailable (bundled.rust:"),
        "the card's live sections name the typed module fault: {symbol}"
    );
    session.close(&fixture).await;
    drop(daemon);
    let _ = std::fs::remove_dir_all(&base);
}

/// References a reply names in prose are masked whatever follows them; other hashes stay.
#[test]
fn prose_references_are_masked_and_nothing_else() {
    let reference = "8ab2ae26df5f5c8e532fbd83009bdff27a57bf8b598b90102c30db448fdc6c75";
    let other = "b".repeat(64);
    assert_eq!(
        mask_text_refs(&format!(
            "edit: unchanged; source_ref {reference}-5; Next: use ide.edit with source_ref {reference}-5\ndigest {other}"
        )),
        format!(
            "edit: unchanged; source_ref <ref>; Next: use ide.edit with source_ref <ref>\ndigest {other}"
        )
    );
}
