//! Explicit Codex and Claude host validation for MCP invocation and native hook lifecycles.
//!
//! A parsed candidate is not an authority claim. A matching trusted `PreToolUse` yields a
//! [`ValidatedInvocation`] before MCP result delivery; later `PostToolUse` is settlement
//! evidence. Consumers still decide whether the host transport and execution profile prove
//! the authority they require.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
};

use serde::Deserialize;
use serde_json::{Map, Value};

const MAX_IDENTIFIER_BYTES: usize = 256;
const MAX_HOOK_METADATA_BYTES: usize = 64 * 1024;
/// Bounds observed and settling calls within one exact channel, host, and actor scope.
const MAX_PENDING_PER_SCOPE: usize = 128;
const MAX_BINDINGS: usize = 64;
/// Bounds independent channels that can retain replay evidence in one daemon lifetime.
const MAX_REPLAY_CHANNELS: usize = 64;
/// Bounds host/actor replay scopes independently within each retained channel.
const MAX_REPLAY_SCOPES_PER_CHANNEL: usize = 64;
/// Bounds retained rejected or completed call identities within one exact scope.
///
/// The allowance matches the former daemon-wide replay budget so one long-lived shipped host
/// actor can complete provider warm-up polling without weakening permanent replay rejection.
const MAX_REPLAYS_PER_SCOPE: usize = 1024;
/// Bounds a selected shell command line before it can be compared against generated bytes.
const MAX_LAUNCH_COMMAND_BYTES: usize = 8 * 1024;
/// The only native tool whose arguments may contribute a foreground-helper launch observation.
const CLAUDE_SHELL_TOOL: &str = "Bash";
const TURN_METADATA: &str = "x-codex-turn-metadata";
/// Claude's trusted MCP `_meta` field; Claude never supplies an actor, session, or sandbox field here.
const CLAUDE_TOOL_USE_ID: &str = "claudecode/toolUseId";

/// Identifies one candidate invocation extracted only from trusted MCP request metadata.
///
/// `actor_id` originates from `_meta.threadId` and `call_id` from `_meta.callId`; neither
/// field comes from tool arguments. This candidate is transport observation, not authority.
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct CandidateInvocation {
    /// Explicit host contract; current trusted MCP metadata creates only Codex candidates.
    host: HostKind,
    /// Exact host actor selected from trusted request metadata.
    actor_id: String,
    /// Exact host tool call selected from trusted request metadata.
    call_id: String,
}

impl CandidateInvocation {
    /// Returns the host thread identity claimed by trusted request metadata.
    pub fn actor_id(&self) -> &str {
        &self.actor_id
    }

    /// Returns the host tool-call identity claimed by trusted request metadata.
    pub fn call_id(&self) -> &str {
        &self.call_id
    }
}

/// Identifies the trusted Application channel-session carrying a hook or MCP invocation.
///
/// Its value is opaque outside Assistance and is accepted only from the private transport
/// attachment after Application has established its endpoint and connection generation.
#[derive(Clone, Eq, Ord, PartialEq, PartialOrd)]
pub struct ChannelSessionRef(String);

impl fmt::Debug for ChannelSessionRef {
    /// Redacts the opaque private transport attachment from diagnostic output.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("ChannelSessionRef(..)")
    }
}

/// Parses one bounded opaque Application attachment into a channel-session reference.
///
/// The attachment must be valid UTF-8 and meet the common identifier bound. Its contents are
/// never logged, rendered, or treated as actor identity by this parser.
pub fn parse_channel_session(attachment: &[u8]) -> Result<ChannelSessionRef, BindingUnavailable> {
    let value = std::str::from_utf8(attachment)
        .map_err(|_| BindingUnavailable::InvalidAttachment)?
        .to_owned();
    checked_identifier(value, "opaque attachment")
        .map(ChannelSessionRef)
        .map_err(|_| BindingUnavailable::InvalidAttachment)
}

/// Identifies one revocable Assistance binding generation for an actor and channel-session.
///
/// Consumers may retain and pass this opaque value back to Assistance but cannot construct,
/// inspect, or turn it into Workspace authority, an Execution permit, or host evidence.
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct BindingRef {
    /// Explicit host contract prevents attachment/actor collisions across adapters.
    host: HostKind,
    /// Exact host actor owning this generation.
    actor_id: String,
    /// Private daemon-scoped transport channel.
    channel: ChannelSessionRef,
    /// Nonzero monotonic generation within this guard.
    generation: u64,
}

impl BindingRef {
    /// Builds one deterministic binding generation for in-crate tests only.
    ///
    /// Production code never constructs a `BindingRef` directly: a generation exists only because
    /// [`HostBindingGuard`] established it from validated host correlation. Test fixtures still
    /// need two *distinct* generations to prove fencing, so this constructor is compiled only under
    /// `cfg(test)` and confers no liveness — a guard that never established it reports it inactive.
    ///
    /// `actor` is the distinguishing Claude actor identity and `generation` is the nonzero
    /// monotonic revision; `channel` is the opaque attachment. Panics if the attachment is not a
    /// valid bounded identifier, which is a fixture error rather than a runtime condition.
    #[cfg(test)]
    pub(crate) fn fixture(actor: &str, channel: &str, generation: u64) -> Self {
        Self {
            host: HostKind::Claude,
            actor_id: actor.to_owned(),
            channel: parse_channel_session(channel.as_bytes())
                .expect("fixture attachment is valid"),
            generation,
        }
    }

    /// Returns a stable opaque persistence key without exposing actor/channel fields or minting proof.
    /// The domain and length framing preserve distinct actor, channel, and generation identities.
    pub(crate) fn fingerprint(&self) -> [u8; 32] {
        let mut hash = blake3::Hasher::new();
        hash.update(b"assistance-binding-identity-v1");
        for value in [
            match self.host {
                HostKind::Codex => b"codex".as_slice(),
                HostKind::Claude => b"claude".as_slice(),
            },
            self.actor_id.as_bytes(),
            self.channel.0.as_bytes(),
            &self.generation.to_le_bytes(),
        ] {
            hash.update(&(value.len() as u64).to_le_bytes());
            hash.update(value);
        }
        *hash.finalize().as_bytes()
    }
}

/// Represents one successful liveness consume for a particular [`BindingRef`] generation.
///
/// It is a transient, non-authorizing result. Consumers must acquire a fresh value at each
/// scoped admission because a later stop can revoke the underlying binding generation.
#[derive(Debug, Eq, PartialEq)]
pub struct ActiveBindingUse(BindingRef);

impl ActiveBindingUse {
    /// Returns the opaque binding reference whose active state was consumed.
    pub fn binding_ref(&self) -> &BindingRef {
        &self.0
    }
}

/// Identifies native per-tool and batch lifecycle points accepted by explicit host adapters.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HookPhase {
    /// The native host is about to execute the selected tool call.
    Pre,
    /// The native host has finished the selected tool call.
    Post,
    /// The native host reported that tool execution failed after it began.
    PostFailure,
    /// The native host denied an exact tool request and ended its matching pending lifecycle.
    PermissionDenied,
    /// The native host has completed a batch without supplying one synthetic tool-call identity.
    PostBatch,
}

/// Names the host contract that supplied one native event; it is never inferred from process state.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum HostKind {
    /// OpenAI Codex hook fields and output contract.
    Codex,
    /// Anthropic Claude Code hook fields and output contract.
    Claude,
}

/// Names how one host receives the project problem feed's status plate (T28B).
///
/// There is no per-feature split: every supported host gets the same plate data, and
/// [`HostKind::feed_delivery`] is the one place that decides the carrier. Whether a carrier is
/// actually used is decided only by [`FeedDelivery::allows_hooks`] and
/// [`FeedDelivery::allows_replies`]; no consumer compares variants directly (T29B §5).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FeedDelivery {
    /// The host relays native post-hooks; due plates ride hook context (Claude).
    Hooks,
    /// The host has no hook delivery for the plate; due plates lead terminal `ide.*` replies.
    Replies,
    /// The host relays native post-hooks and also reads terminal replies (managed Codex, T29B §5).
    ///
    /// This is unconditional: hooks.json is never inspected and no "hooks work" flag is latched,
    /// so a previously working hook that stops running keeps reply delivery available.
    HooksAndReplies,
}

impl FeedDelivery {
    /// Whether this host's native post phases may carry the due plate.
    pub fn allows_hooks(self) -> bool {
        matches!(self, FeedDelivery::Hooks | FeedDelivery::HooksAndReplies)
    }

    /// Whether this host's terminal `ide.*` replies may carry the due plate.
    pub fn allows_replies(self) -> bool {
        matches!(self, FeedDelivery::Replies | FeedDelivery::HooksAndReplies)
    }
}

impl HostKind {
    /// Decides, in this one place, which carriers a host's plate may ride.
    ///
    /// A future third host picks a side here and every feed path follows. Managed Codex takes
    /// [`FeedDelivery::HooksAndReplies`] unconditionally (T29B §5): when the operator installed
    /// and trusted the hooks the native post delivers the plate, and when they are absent or
    /// untrusted the same policy still delivers it on terminal replies.
    pub fn feed_delivery(&self) -> FeedDelivery {
        match self {
            HostKind::Claude => FeedDelivery::Hooks,
            HostKind::Codex => FeedDelivery::HooksAndReplies,
        }
    }
}

/// Holds bounded selected fields extracted from one native Codex or Claude hook payload.
///
/// The parser discards tool input, tool response, cwd, transcript paths, and all other hook
/// payload fields before returning this value.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HookEvent {
    /// Explicit parser contract that accepted the event.
    host: HostKind,
    /// Normalized non-authorizing lifecycle phase.
    phase: HookPhase,
    /// Root session or exact subagent identity selected by the host-specific parser.
    actor_id: String,
    /// Exact tool ID, absent only when the host supplied an uncorrelated batch boundary.
    call_id: Option<String>,
    /// The host's root session identity, retained for both contracts including on child events.
    session_id: Option<String>,
    /// Claude's optional descriptive subagent type; absent for Codex and parent events.
    agent_type: Option<String>,
    /// Bounded shell launch selected only from a Claude `Bash` pre-hook; absent otherwise.
    launch: Option<HookLaunch>,
    /// Whether a post reported explicit failure; `false` for every non-post event.
    failed: bool,
    /// Native tool name retained only for post phases of either host; the name alone selects the
    /// host-specific project-check triggers (EYES-r2 §5, T29B §4) and never carries tool input
    /// or output.
    tool_name: Option<String>,
}

impl HookEvent {
    /// Returns whether this event occurred before or after its native tool execution.
    pub fn phase(&self) -> HookPhase {
        self.phase
    }

    /// Returns the explicit host contract used to validate this event.
    pub fn host(&self) -> HostKind {
        self.host
    }

    /// Returns the selected hook actor: child `agent_id` or root `session_id`.
    pub fn actor_id(&self) -> &str {
        &self.actor_id
    }

    /// Returns the selected hook `tool_use_id`, or an empty value for an uncorrelated batch event.
    pub fn call_id(&self) -> &str {
        self.call_id.as_deref().unwrap_or("")
    }

    /// Returns the optional exact tool identity without fabricating one for `PostToolBatch`.
    pub fn optional_call_id(&self) -> Option<&str> {
        self.call_id.as_deref()
    }

    /// Returns the exact root session identity, retained even for a subagent or child event.
    pub fn session_id(&self) -> Option<&str> {
        self.session_id.as_deref()
    }

    /// Returns Claude's optional declared subagent type without using it as authority.
    pub fn agent_type(&self) -> Option<&str> {
        self.agent_type.as_deref()
    }

    /// Returns whether a post event carried an explicit failure marker.
    ///
    /// `false` means no marker was present, not that success was proven. A post arriving at all
    /// proves the tool ran; a denied tool call produces no post and is handled by deadline expiry
    /// rather than by this flag.
    pub fn failed(&self) -> bool {
        self.failed
    }

    /// Returns the native tool name of a post or post-failure event of either host.
    ///
    /// Absent for pre, permission-denied and batch phases, and whenever the host sent no valid
    /// bounded name.
    pub fn tool_name(&self) -> Option<&str> {
        self.tool_name.as_deref()
    }

    /// Returns the selected shell launch when this was a Claude `Bash` pre-hook.
    ///
    /// Absent for Codex, for post and batch phases, for every non-`Bash` tool, and whenever the
    /// command was missing or exceeded its bound.
    pub fn launch(&self) -> Option<&HookLaunch> {
        self.launch.as_ref()
    }

    /// Builds one bounded Claude launch observation from already selected fields.
    ///
    /// Used by the daemon-side adapter that reconstructs an event from a sanitized transport
    /// observation. Returns `None` for an empty or over-bound command, so a malformed relay can
    /// never produce a launch the recognizer would inspect.
    pub fn with_launch(mut self, command: &str, run_in_background: bool) -> Option<Self> {
        if command.is_empty() || command.len() > MAX_LAUNCH_COMMAND_BYTES {
            return None;
        }
        self.launch = Some(HookLaunch {
            command: command.to_owned(),
            run_in_background,
        });
        Some(self)
    }

    /// Records a relayed explicit post-failure marker on a reconstructed daemon-side event.
    pub fn with_failure(mut self, failed: bool) -> Self {
        self.failed = failed;
        self
    }
}

/// Describes why host binding is unavailable without retaining or reporting raw host data.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BindingUnavailable {
    /// The metadata payload was not valid bounded JSON object input.
    InvalidMetadata,
    /// A required supported field was absent.
    MissingField(&'static str),
    /// A supported field had an empty, non-string, or over-limit value.
    InvalidField(&'static str),
    /// The private Application attachment was not valid bounded opaque channel-session data.
    InvalidAttachment,
    /// The hook phase was not a supported per-tool or post-batch form.
    UnsupportedHookPhase,
    /// A hook could not be linked exactly to one registered MCP candidate.
    Mismatch,
    /// MCP validation arrived before its exact pre-hook, or a post-hook had no invocation.
    MissingPre,
    /// A post-hook arrived after pre-observation but before MCP validation completed.
    MissingInvocation,
    /// An ordinary MCP invocation had no active matching actor/channel-session binding.
    InactiveBinding,
    /// The candidate was observed twice or after it was already validated.
    Replay,
    /// Bounded pending, binding, channel, scope, or replay storage is full.
    CapacityExceeded,
}

/// Reports the lifecycle strength available to a Workspace or Execution consumer.
///
/// `PreObserved` is not an authority claim. `Validated` proves the exact native pre-hook was
/// observed before MCP acceptance; `Settled` records its later matching post-hook evidence.
/// Native observations are recheck hints only; no result attests authority or sandbox enforcement.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum BindingStatus {
    /// A native pre-hook was retained while awaiting matching trusted MCP metadata.
    PreObserved,
    /// Trusted MCP metadata matched a pre-hook before the handler returned its result.
    Validated(ValidatedInvocation),
    /// The matching native post-hook arrived after a validated MCP invocation.
    Settled(ValidatedInvocation),
    /// A complete native hook lifecycle marks this active binding for registered-path recheck.
    /// It proves neither an MCP invocation nor a source effect or successful native command.
    NativeObserved(BindingRef),
    /// Required host data was absent, malformed, mismatched, replayed, or unavailable.
    Unavailable(BindingUnavailable),
}

/// Captures the exact actor, call, and active binding whose pre-hook matched trusted MCP metadata.
///
/// This value is bounded and contains no model arguments, source, prompt, or hook payload.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidatedInvocation {
    actor_id: String,
    call_id: String,
    binding: BindingRef,
    /// Whether this exact start invocation created the binding it validated.
    created_binding: bool,
}

impl ValidatedInvocation {
    /// Returns the exact actor shared by MCP metadata and its pre-hook event.
    pub fn actor_id(&self) -> &str {
        &self.actor_id
    }

    /// Returns the exact call id shared by MCP metadata and its pre-hook event.
    pub fn call_id(&self) -> &str {
        &self.call_id
    }

    /// Returns the immutable active binding generation that this invocation matched.
    pub fn binding_ref(&self) -> &BindingRef {
        &self.binding
    }
}

/// Distinguishes failed correlation from a successfully settled call in one replay record.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ReplayDisposition {
    /// Correlation failed or a native-only lifecycle consumed this call identity.
    Rejected,
    /// A validated invocation received its exact matching post-hook.
    Completed,
}

/// Maps bounded call identities to their permanent outcome within one host/actor scope.
type ReplayCalls = BTreeMap<String, ReplayDisposition>;

/// Maps bounded host/actor scopes to independently budgeted replay records within one channel.
type ChannelReplayScopes = BTreeMap<(HostKind, String), ReplayCalls>;

/// Tracks bounded pre/MCP/post calls plus revocable actor/channel binding generations.
///
/// One guard belongs to one host connection scope. It never silently reactivates a stopped
/// binding: only `establish_start` creates a generation, while ordinary calls use
/// `validate_active`. Claude Stop may close a generation to all external admission while retaining
/// cleanup-only consumes until its already-ready Edit receipts settle. Rejected and completed call
/// evidence is partitioned by channel and scope, bounded without eviction, and survives ordinary
/// stop/start within this guard.
#[derive(Debug, Default)]
pub struct HostBindingGuard {
    /// Valid pre-hooks awaiting their exact MCP invocation on the same private channel.
    pre_observed: BTreeSet<(CandidateInvocation, ChannelSessionRef)>,
    /// Validated calls awaiting a terminal native post, bound to their admitted generation.
    settling: BTreeMap<(CandidateInvocation, ChannelSessionRef), BindingRef>,
    /// Current generation for each host, actor and channel scope.
    bindings: BTreeMap<(HostKind, String, ChannelSessionRef), BindingRef>,
    /// Bindings closed to external admission but retained for exact stop-time cleanup consumes.
    stopping: BTreeSet<BindingRef>,
    /// Last issued nonzero generation; exhaustion refuses a new binding instead of wrapping.
    next_generation: u64,
    /// Coalesced native lifecycle hints, at most one per active binding and no raw tool data.
    native_hints: BTreeSet<BindingRef>,
    /// Rejected and completed call IDs partitioned by channel and then exact host/actor scope.
    replays: BTreeMap<ChannelSessionRef, ChannelReplayScopes>,
}

impl HostBindingGuard {
    /// Establishes a Codex binding directly from trusted managed-MCP metadata.
    ///
    /// This path is reserved for a fresh process-private attachment whose dispatcher explicitly
    /// selected managed Codex mode. It requires no native hook: the trusted MCP adapter has already
    /// separated `_meta.threadId` and `_meta.callId` from model arguments. The call identity is
    /// completed immediately for replay protection, and an existing actor/channel generation is
    /// reused for idempotent explicit starts. Claude and legacy callers continue through their
    /// hook-correlated methods.
    pub fn establish_managed_codex_start(
        &mut self,
        candidate: CandidateInvocation,
        channel: ChannelSessionRef,
    ) -> BindingStatus {
        self.validate_managed_codex(candidate, channel, true)
    }

    /// Validates one ordinary Codex invocation on an active managed-MCP actor/channel binding.
    ///
    /// The trusted candidate never comes from tool arguments. This method cannot establish or
    /// reactivate a binding, rejects repeated call IDs permanently within the guard, and is not
    /// used by hook-correlated legacy or Claude dispatch.
    pub fn validate_managed_codex_active(
        &mut self,
        candidate: CandidateInvocation,
        channel: ChannelSessionRef,
    ) -> BindingStatus {
        self.validate_managed_codex(candidate, channel, false)
    }

    /// Applies the shared bounded binding and replay rules to one direct managed Codex call.
    ///
    /// A native catch-all hook observes the pre phase of this same invocation before the MCP call
    /// arrives, so an exact otherwise-valid buffered pre-observation is permitted and consumed
    /// here rather than rejected as a replay (T29B). Duplicated pre-events, completed or rejected
    /// call IDs, and conflicting settling state are still rejected first, and completion is
    /// recorded exactly as before: the call's own later native post is then an ordinary completed
    /// replay and stays silent.
    fn validate_managed_codex(
        &mut self,
        candidate: CandidateInvocation,
        channel: ChannelSessionRef,
        establish: bool,
    ) -> BindingStatus {
        let invocation = (candidate.clone(), channel.clone());
        if candidate.host != HostKind::Codex
            || self.replay_disposition(&candidate, &channel).is_some()
            || self.settling.contains_key(&invocation)
        {
            return BindingStatus::Unavailable(BindingUnavailable::Replay);
        }
        self.pre_observed.remove(&invocation);
        if self.replay_scope_saturated(&candidate, &channel)
            || self.ensure_replay_scope(&candidate, &channel).is_err()
        {
            return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
        }
        let binding_key = (candidate.host, candidate.actor_id.clone(), channel.clone());
        let (binding, created_binding) = match self.bindings.get(&binding_key).cloned() {
            Some(binding) => (binding, false),
            None if establish => {
                if self.bindings.len() >= MAX_BINDINGS {
                    return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
                }
                let Some(generation) = self.next_generation.checked_add(1) else {
                    return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
                };
                self.next_generation = generation;
                let binding = BindingRef {
                    host: candidate.host,
                    actor_id: candidate.actor_id.clone(),
                    channel,
                    generation,
                };
                self.bindings.insert(binding_key, binding.clone());
                (binding, true)
            }
            None => {
                self.record_replay(&invocation, ReplayDisposition::Rejected)
                    .expect("the checked managed replay scope has capacity");
                return BindingStatus::Unavailable(BindingUnavailable::InactiveBinding);
            }
        };
        self.record_replay(&invocation, ReplayDisposition::Completed)
            .expect("the checked managed replay scope has capacity");
        BindingStatus::Validated(validated(candidate, binding, created_binding))
    }

    /// Establishes an explicit start binding after its exact native pre-hook is already observed.
    ///
    /// Missing pre-observation rejects this invocation permanently within the daemon lifetime.
    /// A current binding for the same actor/channel is reused for an idempotent explicit start.
    /// After `stop_binding` or `stop`, a later explicit start creates a fresh generation.
    pub fn establish_start(
        &mut self,
        candidate: CandidateInvocation,
        channel: ChannelSessionRef,
    ) -> BindingStatus {
        let invocation = (candidate.clone(), channel.clone());
        if self.replay_disposition(&candidate, &channel).is_some()
            || self.settling.contains_key(&invocation)
        {
            return BindingStatus::Unavailable(BindingUnavailable::Replay);
        }
        if self.replay_scope_saturated(&candidate, &channel) {
            return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
        }
        if !self.pre_observed.contains(&invocation) {
            if self
                .record_replay(&invocation, ReplayDisposition::Rejected)
                .is_err()
            {
                return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
            }
            return BindingStatus::Unavailable(BindingUnavailable::MissingPre);
        }
        let binding_key = (candidate.host, candidate.actor_id.clone(), channel.clone());
        let (binding, created_binding) = if let Some(existing) = self.bindings.get(&binding_key) {
            if self.stopping.contains(existing) {
                self.record_replay(&invocation, ReplayDisposition::Rejected)
                    .expect("the checked replay scope has capacity");
                return BindingStatus::Unavailable(BindingUnavailable::InactiveBinding);
            }
            (existing.clone(), false)
        } else {
            if self.bindings.len() >= MAX_BINDINGS {
                return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
            }
            let Some(generation) = self.next_generation.checked_add(1) else {
                return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
            };
            self.next_generation = generation;
            let binding = BindingRef {
                host: candidate.host,
                actor_id: candidate.actor_id.clone(),
                channel,
                generation,
            };
            self.bindings.insert(binding_key, binding.clone());
            (binding, true)
        };
        self.pre_observed.remove(&invocation);
        self.settling.insert(invocation, binding.clone());
        BindingStatus::Validated(validated(candidate, binding, created_binding))
    }

    /// Validates an ordinary MCP candidate against its active matching actor/channel binding.
    ///
    /// Failed ordering is retained as bounded replay evidence and cannot be repaired by late hooks.
    /// This path never creates or revives a binding. Its pre-observation is consumed even when
    /// no active binding exists, so a later start cannot validate an old ordinary call.
    pub fn validate_active(
        &mut self,
        candidate: CandidateInvocation,
        channel: ChannelSessionRef,
    ) -> BindingStatus {
        let invocation = (candidate.clone(), channel.clone());
        if self.replay_disposition(&candidate, &channel).is_some()
            || self.settling.contains_key(&invocation)
        {
            return BindingStatus::Unavailable(BindingUnavailable::Replay);
        }
        if self.replay_scope_saturated(&candidate, &channel) {
            return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
        }
        if !self.pre_observed.remove(&invocation) {
            if self
                .record_replay(&invocation, ReplayDisposition::Rejected)
                .is_err()
            {
                return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
            }
            return BindingStatus::Unavailable(BindingUnavailable::MissingPre);
        }
        let Some(binding) = self
            .bindings
            .get(&(candidate.host, candidate.actor_id.clone(), channel))
            .cloned()
        else {
            if self
                .record_replay(&invocation, ReplayDisposition::Rejected)
                .is_err()
            {
                return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
            }
            return BindingStatus::Unavailable(BindingUnavailable::InactiveBinding);
        };
        if self.stopping.contains(&binding) {
            self.record_replay(&invocation, ReplayDisposition::Rejected)
                .expect("the checked replay scope has capacity");
            return BindingStatus::Unavailable(BindingUnavailable::InactiveBinding);
        }
        self.settling.insert(invocation, binding.clone());
        BindingStatus::Validated(validated(candidate, binding, false))
    }

    /// Buffers a native pre-hook or records a per-tool/batch post for a channel-bound invocation.
    ///
    /// Duplicate pre-hooks and post-before-MCP lifecycles prevent later MCP validation.
    /// For an already active binding, a complete Pre/Post without MCP also coalesces one
    /// native-change hint. Failed commands and edit/delete/rename lifecycles use the same hint;
    /// tool payloads are never interpreted as proof of effects.
    /// A pre-hook is not an authority claim. A post-hook never gates MCP result acceptance: it
    /// only settles a call that was already validated by `establish_start` or `validate_active`.
    pub fn observe_hook(&mut self, event: HookEvent, channel: ChannelSessionRef) -> BindingStatus {
        if event.phase == HookPhase::PostBatch {
            // Claude's PostToolUse already fires once per exact tool call; its uncorrelated batch
            // boundary must never coalesce a native-change hint that Claude never actually proved.
            if event.host == HostKind::Claude {
                return BindingStatus::Unavailable(BindingUnavailable::UnsupportedHookPhase);
            }
            let Some(binding) = self
                .bindings
                .get(&(event.host, event.actor_id, channel))
                .cloned()
            else {
                return BindingStatus::Unavailable(BindingUnavailable::InactiveBinding);
            };
            self.native_hints.insert(binding.clone());
            return BindingStatus::NativeObserved(binding);
        }
        // Selected before the candidate's partial move out of `event`.
        let self_mcp_post = super::problems::is_self_mcp_tool_name(event.tool_name.as_deref());
        let candidate = CandidateInvocation {
            host: event.host,
            actor_id: event.actor_id,
            call_id: event
                .call_id
                .expect("non-batch hook parsers require a tool-use identity"),
        };
        let invocation = (candidate.clone(), channel);
        if let Some(disposition) = self.replay_disposition(&candidate, &invocation.1) {
            return BindingStatus::Unavailable(match disposition {
                ReplayDisposition::Rejected => BindingUnavailable::Mismatch,
                ReplayDisposition::Completed => BindingUnavailable::Replay,
            });
        }
        if self.replay_scope_saturated(&candidate, &invocation.1)
            || self.ensure_replay_scope(&candidate, &invocation.1).is_err()
        {
            return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
        }
        match event.phase {
            HookPhase::Pre
                if self.pre_observed.contains(&invocation)
                    || self.settling.contains_key(&invocation) =>
            {
                self.pre_observed.remove(&invocation);
                self.settling.remove(&invocation);
                self.record_replay(&invocation, ReplayDisposition::Rejected)
                    .expect("the checked rejection scope has capacity");
                BindingStatus::Unavailable(BindingUnavailable::Replay)
            }
            HookPhase::Pre => {
                if self.pending_in_scope(&candidate, &invocation.1) >= MAX_PENDING_PER_SCOPE {
                    return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
                }
                self.pre_observed.insert(invocation);
                BindingStatus::PreObserved
            }
            HookPhase::Post | HookPhase::PostFailure => {
                let failed = event.phase == HookPhase::PostFailure;
                if self.pre_observed.remove(&invocation) {
                    let binding = self
                        .bindings
                        .get(&(candidate.host, candidate.actor_id, invocation.1.clone()))
                        .cloned();
                    self.record_replay(&invocation, ReplayDisposition::Rejected)
                        .expect("the checked rejection scope has capacity");
                    // A post naming this product's own MCP tool, paired with a still-buffered
                    // pre, proves the MCP call was rejected before managed admission ever ran
                    // (an admitted call consumes its pre and records completion): the call id is
                    // recorded rejected above, and the post stays a silent rejection with no
                    // native hint, epoch advance, check trigger, or plate (T29B final review 4).
                    if self_mcp_post {
                        return BindingStatus::Unavailable(BindingUnavailable::MissingInvocation);
                    }
                    if let Some(binding) = binding {
                        self.native_hints.insert(binding.clone());
                        return BindingStatus::NativeObserved(binding);
                    }
                    return BindingStatus::Unavailable(BindingUnavailable::MissingInvocation);
                }
                let Some(binding) = self.settling.get(&invocation).cloned() else {
                    self.record_replay(&invocation, ReplayDisposition::Rejected)
                        .expect("the checked rejection scope has capacity");
                    return BindingStatus::Unavailable(BindingUnavailable::Mismatch);
                };
                if self
                    .record_replay(&invocation, ReplayDisposition::Completed)
                    .is_err()
                {
                    return BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded);
                }
                self.settling.remove(&invocation);
                if failed {
                    self.native_hints.insert(binding.clone());
                }
                BindingStatus::Settled(validated(candidate, binding, false))
            }
            HookPhase::PermissionDenied => {
                if self.pre_observed.remove(&invocation)
                    || self.settling.remove(&invocation).is_some()
                {
                    self.record_replay(&invocation, ReplayDisposition::Rejected)
                        .expect("the checked rejection scope has capacity");
                    return BindingStatus::Unavailable(BindingUnavailable::MissingInvocation);
                }
                self.record_replay(&invocation, ReplayDisposition::Rejected)
                    .expect("the checked rejection scope has capacity");
                BindingStatus::Unavailable(BindingUnavailable::Mismatch)
            }
            HookPhase::PostBatch => unreachable!("batch hooks return before invocation matching"),
        }
    }

    /// Consumes a coalesced native lifecycle hint for one currently active binding.
    ///
    /// `true` requests a fresh bounded registered-path reconciliation, never an assumed source
    /// effect. `false` means no unconsumed hint. Stopped/stale generations return unavailable;
    /// no path, command success, Workspace authority or Execution permit is inferred.
    pub fn take_native_change_hint(
        &mut self,
        binding: &BindingRef,
    ) -> Result<bool, BindingUnavailable> {
        self.check_active(binding)?;
        Ok(self.native_hints.remove(binding))
    }

    /// Requests registered-path reconciliation for one active managed Codex binding.
    ///
    /// Unlike a native hook observation, this records no tool lifecycle or claimed source effect.
    /// It only coalesces the same worker hint so the next read job reuses existing reconciliation.
    pub(crate) fn request_registered_path_reconciliation(
        &mut self,
        binding: &BindingRef,
    ) -> Result<(), BindingUnavailable> {
        self.check_active(binding)?;
        self.native_hints.insert(binding.clone());
        Ok(())
    }

    /// Returns retained rejection or completion evidence for one exact scoped call.
    fn replay_disposition(
        &self,
        candidate: &CandidateInvocation,
        channel: &ChannelSessionRef,
    ) -> Option<ReplayDisposition> {
        self.replays
            .get(channel)?
            .get(&(candidate.host, candidate.actor_id.clone()))?
            .get(&candidate.call_id)
            .copied()
    }

    /// Returns whether one channel-local host/actor scope exhausted its replay budget.
    fn replay_scope_saturated(
        &self,
        candidate: &CandidateInvocation,
        channel: &ChannelSessionRef,
    ) -> bool {
        self.replays
            .get(channel)
            .and_then(|scopes| scopes.get(&(candidate.host, candidate.actor_id.clone())))
            .is_some_and(|calls| calls.len() >= MAX_REPLAYS_PER_SCOPE)
    }

    /// Counts observed and validated-but-unsettled calls in one exact capacity scope.
    fn pending_in_scope(
        &self,
        candidate: &CandidateInvocation,
        channel: &ChannelSessionRef,
    ) -> usize {
        self.pre_observed
            .iter()
            .filter(|(observed, observed_channel)| {
                observed.host == candidate.host
                    && observed.actor_id == candidate.actor_id
                    && observed_channel == channel
            })
            .count()
            + self
                .settling
                .keys()
                .filter(|(observed, observed_channel)| {
                    observed.host == candidate.host
                        && observed.actor_id == candidate.actor_id
                        && observed_channel == channel
                })
                .count()
    }

    /// Reserves replay storage within independent channel and host/actor budgets.
    fn ensure_replay_scope(
        &mut self,
        candidate: &CandidateInvocation,
        channel: &ChannelSessionRef,
    ) -> Result<(), BindingUnavailable> {
        if !self.replays.contains_key(channel) {
            if self.replays.len() >= MAX_REPLAY_CHANNELS {
                return Err(BindingUnavailable::CapacityExceeded);
            }
            self.replays.insert(channel.clone(), BTreeMap::new());
        }
        let scopes = self
            .replays
            .get_mut(channel)
            .expect("the replay channel was just ensured");
        let scope = (candidate.host, candidate.actor_id.clone());
        if scopes.contains_key(&scope) {
            return Ok(());
        }
        if scopes.len() >= MAX_REPLAY_SCOPES_PER_CHANNEL {
            return Err(BindingUnavailable::CapacityExceeded);
        }
        scopes.insert(scope, BTreeMap::new());
        Ok(())
    }

    /// Retains one rejected or completed call without eviction or cross-channel budget sharing.
    fn record_replay(
        &mut self,
        invocation: &(CandidateInvocation, ChannelSessionRef),
        disposition: ReplayDisposition,
    ) -> Result<(), BindingUnavailable> {
        self.ensure_replay_scope(&invocation.0, &invocation.1)?;
        let calls = self
            .replays
            .get_mut(&invocation.1)
            .expect("the replay channel was just ensured")
            .get_mut(&(invocation.0.host, invocation.0.actor_id.clone()))
            .expect("the replay scope was just ensured");
        if calls.contains_key(&invocation.0.call_id) {
            return Ok(());
        }
        if calls.len() >= MAX_REPLAYS_PER_SCOPE {
            return Err(BindingUnavailable::CapacityExceeded);
        }
        calls.insert(invocation.0.call_id.clone(), disposition);
        Ok(())
    }

    /// Recovers the exact actor a matching Claude pre-hook already registered for one MCP call.
    ///
    /// Claude's trusted MCP metadata carries only `claudecode/toolUseId`, never an actor, session,
    /// or sandbox field. The actor must come from the trusted native pre-hook already observed for
    /// this exact channel and tool call. Zero or more than one matching pre-observation is rejected
    /// rather than guessed, so this can never accept a cross-actor or wrong-channel replay.
    fn recover_claude_candidate(
        &self,
        call_id: &str,
        channel: &ChannelSessionRef,
    ) -> Result<CandidateInvocation, BindingUnavailable> {
        let mut matches = self.pre_observed.iter().filter(|(candidate, observed)| {
            candidate.host == HostKind::Claude
                && candidate.call_id == call_id
                && observed == channel
        });
        let candidate = matches
            .next()
            .ok_or(BindingUnavailable::MissingPre)?
            .0
            .clone();
        if matches.next().is_some() {
            return Err(BindingUnavailable::Mismatch);
        }
        Ok(candidate)
    }

    /// Establishes a Claude MCP start binding after recovering its exact registered pre-hook actor.
    ///
    /// This is the only entry point for a Claude `_meta["claudecode/toolUseId"]` MCP candidate:
    /// the caller never constructs a [`CandidateInvocation`] directly from Claude MCP metadata.
    pub fn establish_start_claude(
        &mut self,
        call_id: &str,
        channel: ChannelSessionRef,
    ) -> BindingStatus {
        match self.recover_claude_candidate(call_id, &channel) {
            Ok(candidate) => self.establish_start(candidate, channel),
            Err(error) => BindingStatus::Unavailable(error),
        }
    }

    /// Validates an ordinary Claude MCP call after recovering its exact registered pre-hook actor.
    pub fn validate_active_claude(
        &mut self,
        call_id: &str,
        channel: ChannelSessionRef,
    ) -> BindingStatus {
        match self.recover_claude_candidate(call_id, &channel) {
            Ok(candidate) => self.validate_active(candidate, channel),
            Err(error) => BindingStatus::Unavailable(error),
        }
    }

    /// Checks whether one immutable binding generation remains active at this exact boundary.
    pub fn check_active(&self, binding: &BindingRef) -> Result<(), BindingUnavailable> {
        let key = (
            binding.host,
            binding.actor_id.clone(),
            binding.channel.clone(),
        );
        (self.bindings.get(&key) == Some(binding) && !self.stopping.contains(binding))
            .then_some(())
            .ok_or(BindingUnavailable::InactiveBinding)
    }

    /// Consumes current liveness for one scoped Workspace or Execution admission.
    ///
    /// Calls are serialized with `stop_binding` and `stop`: a consume after their revocation
    /// point fails. The returned value is not a durable permit and must not be reused.
    pub fn consume_active(
        &mut self,
        binding: &BindingRef,
    ) -> Result<ActiveBindingUse, BindingUnavailable> {
        self.check_active(binding)?;
        Ok(ActiveBindingUse(binding.clone()))
    }

    /// Closes external admission while retaining only exact cleanup authority for this generation.
    ///
    /// After this transition, ordinary validation, helper claims and active consumes fail. The
    /// caller may use `consume_stopping` solely to settle already-ready Edit evidence before
    /// [`Self::stop_binding`] removes the generation permanently. Repeated or stale transitions are
    /// rejected and no new generation is created.
    pub fn begin_stop(&mut self, binding: &BindingRef) -> Result<(), BindingUnavailable> {
        let key = (
            binding.host,
            binding.actor_id.clone(),
            binding.channel.clone(),
        );
        if self.bindings.get(&key) != Some(binding) || !self.stopping.insert(binding.clone()) {
            return Err(BindingUnavailable::InactiveBinding);
        }
        self.native_hints.remove(binding);
        Ok(())
    }

    /// Consumes cleanup-only liveness for the exact generation already closed by `begin_stop`.
    ///
    /// This cannot admit a helper claim or an ordinary Workspace operation because those routes
    /// use [`Self::consume_active`], which rejects stopping bindings. The returned transient value
    /// is valid only for settlement of ready tickets captured by that Stop invocation.
    pub(crate) fn consume_stopping(
        &mut self,
        binding: &BindingRef,
    ) -> Result<ActiveBindingUse, BindingUnavailable> {
        let key = (
            binding.host,
            binding.actor_id.clone(),
            binding.channel.clone(),
        );
        (self.bindings.get(&key) == Some(binding) && self.stopping.contains(binding))
            .then(|| ActiveBindingUse(binding.clone()))
            .ok_or(BindingUnavailable::InactiveBinding)
    }

    /// Removes only one just-established generation after its own admission refused it.
    ///
    /// Use this, never [`Self::stop_binding`], when an `ide.start` established a binding and the
    /// same call then refused admission. It removes exactly that generation and its settling entry
    /// and nothing else: unrelated pre-observations in the same scope are untouched, no replay
    /// record is written, and a concurrently valid retry is neither revoked nor poisoned. Leaving
    /// the generation in place instead would advertise an active binding that never became usable.
    ///
    /// Returns [`BindingUnavailable::InactiveBinding`] when the supplied generation is not the
    /// currently active one, which means it was already replaced or stopped and must not be
    /// removed by this caller.
    pub fn rollback_established(&mut self, binding: &BindingRef) -> Result<(), BindingUnavailable> {
        let key = (
            binding.host,
            binding.actor_id.clone(),
            binding.channel.clone(),
        );
        if self.bindings.get(&key) != Some(binding) {
            return Err(BindingUnavailable::InactiveBinding);
        }
        self.bindings.remove(&key);
        self.stopping.remove(binding);
        self.native_hints.remove(binding);
        self.settling.retain(|_, owner| owner != binding);
        Ok(())
    }

    /// Revokes one generation and rejects its pending pre-hooks; later post settlement remains valid.
    pub fn stop_binding(&mut self, binding: &BindingRef) -> Result<(), BindingUnavailable> {
        let key = (
            binding.host,
            binding.actor_id.clone(),
            binding.channel.clone(),
        );
        if self.bindings.get(&key) != Some(binding) {
            return Err(BindingUnavailable::InactiveBinding);
        }
        self.bindings.remove(&key);
        self.stopping.remove(binding);
        self.native_hints.remove(binding);
        let pending: Vec<_> = self
            .pre_observed
            .iter()
            .filter(|invocation| {
                invocation.0.host == binding.host
                    && invocation.0.actor_id == binding.actor_id
                    && invocation.1 == binding.channel
            })
            .cloned()
            .collect();
        for invocation in &pending {
            // A full scope already rejects every later call, so retaining another ID is unnecessary.
            let _ = self.record_replay(invocation, ReplayDisposition::Rejected);
        }
        self.pre_observed.retain(|invocation| {
            invocation.0.host != binding.host
                || invocation.0.actor_id != binding.actor_id
                || invocation.1 != binding.channel
        });
        Ok(())
    }

    /// Revokes every active binding and discards unmatched pre-hooks in this host scope.
    ///
    /// Later explicit starts remain permitted and receive fresh generations; later post-hooks
    /// can still settle calls that were validated before this stop.
    pub fn stop(&mut self) {
        self.pre_observed.clear();
        self.bindings.clear();
        self.stopping.clear();
        self.native_hints.clear();
    }
}

/// Builds a public invocation record from a bounded candidate and immutable binding reference.
fn validated(
    candidate: CandidateInvocation,
    binding: BindingRef,
    created_binding: bool,
) -> ValidatedInvocation {
    ValidatedInvocation {
        actor_id: candidate.actor_id,
        call_id: candidate.call_id,
        binding,
        created_binding,
    }
}

/// Parses only Codex's trusted MCP `_meta` fields needed for a candidate lifecycle.
///
/// Call this only at trusted MCP ingress after rmcp has separated request metadata from tool
/// arguments. The required `x-codex-turn-metadata` object is checked for host support but not
/// retained, and arbitrary `_meta` or argument fields cannot contribute identity.
pub fn parse_candidate(
    meta: &Map<String, Value>,
) -> Result<CandidateInvocation, BindingUnavailable> {
    if !meta.get(TURN_METADATA).is_some_and(Value::is_object) {
        return Err(BindingUnavailable::MissingField(TURN_METADATA));
    }
    Ok(CandidateInvocation {
        host: HostKind::Codex,
        actor_id: required_identifier(meta, "threadId")?,
        call_id: required_identifier(meta, "callId")?,
    })
}

/// Selects exactly one complete supported MCP host metadata contract.
///
/// Codex identity and turn fields cannot coexist with Claude's tool-use field.
/// A lone field from an otherwise incomplete contract is rejected rather than used to guess a host.
pub fn parse_host_kind(meta: &Map<String, Value>) -> Result<HostKind, BindingUnavailable> {
    let has_codex_field = [TURN_METADATA, "threadId", "callId"]
        .iter()
        .any(|field| meta.contains_key(*field));
    let has_claude_field = meta.contains_key(CLAUDE_TOOL_USE_ID);
    match (has_codex_field, has_claude_field) {
        (true, false) => parse_candidate(meta).map(|_| HostKind::Codex),
        (false, true) => parse_claude_call_id(meta).map(|_| HostKind::Claude),
        _ => Err(BindingUnavailable::InvalidMetadata),
    }
}

/// Parses only Claude's trusted MCP `_meta["claudecode/toolUseId"]` field.
///
/// Call this only at trusted MCP ingress. Real Claude Code 2.1.267 MCP request metadata carries
/// this exact bounded string and an unrelated `progressToken`; it never carries an actor, session,
/// agent, or sandbox field. This call ID alone is not a candidate: [`HostBindingGuard::establish_start_claude`]
/// and [`HostBindingGuard::validate_active_claude`] recover the actor from the matching pre-hook.
pub fn parse_claude_call_id(meta: &Map<String, Value>) -> Result<String, BindingUnavailable> {
    required_identifier(meta, CLAUDE_TOOL_USE_ID)
}

/// Parses one bounded Codex hook payload while retaining host, phase, actor, root session, and
/// call ID plus the post-phase tool name.
///
/// Root hooks identify the actor with `session_id`, which is validated and retained. Native child
/// hooks retain that root session and additionally provide `agent_id`; the child ID is the actor
/// while the root session stays attached as isolation context. A payload with neither identity,
/// an invalid identity, or duplicate known JSON keys is unavailable. A valid bounded `tool_name`
/// is retained only for the post phases; an invalid name is dropped rather than rejecting the
/// event. The parser never returns tool input/output, source, cwd, transcript paths, or unknown
/// fields.
pub fn parse_hook_event(payload: &[u8]) -> Result<HookEvent, BindingUnavailable> {
    if payload.len() > MAX_HOOK_METADATA_BYTES {
        return Err(BindingUnavailable::InvalidMetadata);
    }
    let payload: CodexHookPayload =
        serde_json::from_slice(payload).map_err(|_| BindingUnavailable::InvalidMetadata)?;
    let phase = match payload.hook_event_name.as_str() {
        "PreToolUse" => HookPhase::Pre,
        "PostToolUse" => HookPhase::Post,
        "PostToolUseFailure" => HookPhase::PostFailure,
        "PermissionDenied" => HookPhase::PermissionDenied,
        "PostToolBatch" => HookPhase::PostBatch,
        _ => return Err(BindingUnavailable::UnsupportedHookPhase),
    };
    let session_id = payload
        .session_id
        .map(|value| checked_identifier(value, "session_id"))
        .transpose()?;
    let agent_id = payload
        .agent_id
        .map(|value| checked_identifier(value, "agent_id"))
        .transpose()?;
    let actor_id = match agent_id {
        Some(actor) => actor,
        None => session_id
            .clone()
            .ok_or(BindingUnavailable::MissingField("hook actor"))?,
    };
    let tool_name = match phase {
        HookPhase::Post | HookPhase::PostFailure => payload
            .tool_name
            .clone()
            .and_then(|name| checked_identifier(name, "tool_name").ok()),
        _ => None,
    };
    Ok(HookEvent {
        host: HostKind::Codex,
        phase,
        actor_id,
        call_id: match (phase, payload.tool_use_id) {
            (HookPhase::PostBatch, None) => None,
            (_, Some(value)) => Some(checked_identifier(value, "tool_use_id")?),
            _ => return Err(BindingUnavailable::MissingField("tool_use_id")),
        },
        session_id,
        agent_type: None,
        launch: None,
        failed: false,
        tool_name,
    })
}

/// Parses Claude Code's documented hook identity without treating permission mode as a sandbox.
///
/// `session_id` is always retained. A subagent is identified by its exact optional `agent_id`,
/// while a parent is identified by `session_id`; `agent_type` is descriptive only. `tool_name` is
/// retained only for `PostToolUse`/`PostToolUseFailure` and only when it is a valid bounded
/// identifier; an invalid name is dropped rather than rejecting the event. Tool input, output,
/// permission mode, paths, source, and unknown fields are discarded. `PostToolBatch` deliberately
/// has no fabricated call identity.
pub fn parse_claude_hook_event(payload: &[u8]) -> Result<HookEvent, BindingUnavailable> {
    if payload.len() > MAX_HOOK_METADATA_BYTES {
        return Err(BindingUnavailable::InvalidMetadata);
    }
    let payload: ClaudeHookPayload =
        serde_json::from_slice(payload).map_err(|_| BindingUnavailable::InvalidMetadata)?;
    let phase = match payload.hook_event_name.as_str() {
        "PreToolUse" => HookPhase::Pre,
        "PostToolUse" => HookPhase::Post,
        "PostToolUseFailure" => HookPhase::PostFailure,
        "PermissionDenied" => HookPhase::PermissionDenied,
        "PostToolBatch" => HookPhase::PostBatch,
        _ => return Err(BindingUnavailable::UnsupportedHookPhase),
    };
    let session_id = checked_identifier(payload.session_id, "session_id")?;
    let agent_id = payload
        .agent_id
        .map(|value| checked_identifier(value, "agent_id"))
        .transpose()?;
    let agent_type = payload
        .agent_type
        .map(|value| checked_identifier(value, "agent_type"))
        .transpose()?;
    let call_id = match (phase, payload.tool_use_id) {
        (HookPhase::PostBatch, None) => None,
        (_, Some(value)) => Some(checked_identifier(value, "tool_use_id")?),
        _ => return Err(BindingUnavailable::MissingField("tool_use_id")),
    };
    // A launch observation is selected only from a `Bash` pre-hook, and only its two shell
    // fields. Every other tool's arguments are discarded here, so nothing about an unrelated
    // tool call is ever retained or relayed to the daemon.
    let tool_name = match phase {
        HookPhase::Post | HookPhase::PostFailure => payload
            .tool_name
            .clone()
            .and_then(|name| checked_identifier(name, "tool_name").ok()),
        _ => None,
    };
    let launch = match (phase, payload.tool_name.as_deref(), payload.tool_input) {
        (HookPhase::Pre, Some(CLAUDE_SHELL_TOOL), Some(input)) => input
            .command
            .filter(|command| !command.is_empty() && command.len() <= MAX_LAUNCH_COMMAND_BYTES)
            .map(|command| HookLaunch {
                command,
                run_in_background: input.run_in_background.unwrap_or(false),
            }),
        _ => None,
    };
    // Only an explicit marker counts as failure; an absent or unrecognized response never
    // downgrades a completed tool call, and never upgrades a denied one into a completion.
    let failed = phase == HookPhase::Post
        && payload.tool_response.as_ref().is_some_and(|response| {
            response.success == Some(false)
                || response.is_error == Some(true)
                || response.interrupted == Some(true)
        });
    Ok(HookEvent {
        host: HostKind::Claude,
        phase,
        actor_id: agent_id.unwrap_or_else(|| session_id.clone()),
        call_id,
        session_id: Some(session_id),
        agent_type,
        launch,
        failed,
        tool_name,
    })
}

/// Selects only Codex correlation fields plus the post-phase tool name, rejects duplicate known
/// JSON keys, and discards every other host field (cwd, model, permission mode, tool input and
/// response, transcript path, turn ID, agent type) that real codex-cli payloads carry.
#[derive(Deserialize)]
struct CodexHookPayload {
    /// Native lifecycle name, restricted to pre, post, or post-batch after decoding.
    hook_event_name: String,
    /// Root session identity; retained alongside `agent_id` by native child events.
    session_id: Option<String>,
    /// Child actor identity; absent/null for a root event, bounded after decoding.
    agent_id: Option<String>,
    /// Exact native tool-call identifier, optional only for `PostToolBatch`.
    tool_use_id: Option<String>,
    /// Native tool name; retained only for the post phases after bounded validation.
    tool_name: Option<String>,
}

/// Selects only Claude Code correlation fields while Serde rejects duplicate known keys.
#[derive(Deserialize)]
struct ClaudeHookPayload {
    /// Native lifecycle name accepted by the bounded Claude adapter.
    hook_event_name: String,
    /// Required exact Claude session identity for parent and subagent events.
    session_id: String,
    /// Optional exact subagent identity; when absent the session is the parent actor.
    agent_id: Option<String>,
    /// Optional descriptive subagent type, retained but never interpreted as authority.
    agent_type: Option<String>,
    /// Exact native tool identity; optional only for `PostToolBatch`.
    tool_use_id: Option<String>,
    /// Native tool name; selects a shell launch on pre-hooks and is retained on post phases.
    tool_name: Option<String>,
    /// Native tool arguments; only a shell launch's two selected fields survive parsing.
    #[serde(default, deserialize_with = "selected_fields")]
    tool_input: Option<ClaudeToolInput>,
    /// Native tool result; only explicit failure markers survive parsing.
    #[serde(default, deserialize_with = "selected_fields")]
    tool_response: Option<ClaudeToolResponse>,
}

/// Keeps one optional native field's selected shape without letting any other shape reject the hook.
///
/// Claude types `tool_input` and `tool_response` freely: a shell call carries an object, while many
/// tools report a bare string or array. Only the object form carries anything this adapter reads,
/// so any other shape must yield `None` rather than failing the whole payload — a rejected payload
/// loses the actor and call correlation the binding depends on, which is a far worse outcome than
/// not observing a launch or a failure marker. The intermediate value is dropped here, so no raw
/// host field survives into [`HookEvent`].
fn selected_fields<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::de::DeserializeOwned,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    Ok(T::deserialize(value).ok())
}

/// Selects only the explicit failure markers a post payload may carry.
///
/// Claude emits `PostToolUse` for a tool that ran, whether it succeeded or failed, and emits no
/// post at all when permission was denied. So a post's mere arrival proves execution, not success:
/// only these explicit markers distinguish the two. Output, content and every other field of the
/// response are discarded before this value exists.
#[derive(Deserialize)]
struct ClaudeToolResponse {
    /// Explicit success flag when the host supplies one.
    success: Option<bool>,
    /// Explicit error flag when the host supplies one instead.
    is_error: Option<bool>,
    /// Whether the host interrupted the tool before it finished.
    interrupted: Option<bool>,
}

/// Selects only the two shell fields a foreground-helper launch can be recognized by.
///
/// Every other `tool_input` field — file paths, patches, prompts, URLs, edit content — is
/// discarded by Serde before this value exists, and even these two are dropped for any tool
/// other than `Bash`.
#[derive(Deserialize)]
struct ClaudeToolInput {
    /// Raw shell command line, compared byte-for-byte and never parsed as shell syntax.
    command: Option<String>,
    /// Native background flag; a background launch can never be a foreground helper.
    run_in_background: Option<bool>,
}

/// Holds the bounded shell launch a native pre-hook offered for exact-byte recognition.
///
/// This is transport observation only. It confers nothing: the daemon compares it against bytes
/// it generated itself and otherwise discards it, and no hook path turns it into a permission
/// decision, an updated tool input, or authority of any kind.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HookLaunch {
    /// Exact command line as the host received it, never rewritten.
    command: String,
    /// Whether the host was asked to run this command detached from the tool call.
    run_in_background: bool,
}

impl HookLaunch {
    /// Returns the exact unmodified command bytes offered by the native tool call.
    pub fn command(&self) -> &str {
        &self.command
    }

    /// Returns whether the launch was requested in the background.
    pub fn run_in_background(&self) -> bool {
        self.run_in_background
    }
}

/// Reads a required bounded string field without reporting its raw value.
fn required_identifier(
    object: &Map<String, Value>,
    field: &'static str,
) -> Result<String, BindingUnavailable> {
    let Some(value) = object.get(field) else {
        return Err(BindingUnavailable::MissingField(field));
    };
    let Some(value) = value.as_str() else {
        return Err(BindingUnavailable::InvalidField(field));
    };
    checked_identifier(value.to_owned(), field)
}

/// Enforces the fixed identifier memory bound and rejects empty values.
fn checked_identifier(value: String, field: &'static str) -> Result<String, BindingUnavailable> {
    if value.is_empty() || value.len() > MAX_IDENTIFIER_BYTES {
        return Err(BindingUnavailable::InvalidField(field));
    }
    Ok(value)
}

/// Exercises bounded host-correlation state using parser-shaped metadata and hook observations.
#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Builds one bounded channel reference for state-machine tests.
    fn channel(name: &str) -> ChannelSessionRef {
        parse_channel_session(name.as_bytes()).expect("test channel is valid")
    }

    /// Builds one Codex candidate through the same metadata parser used at trusted ingress.
    fn codex_candidate(actor: &str, call: &str) -> CandidateInvocation {
        parse_candidate(
            json!({
                "threadId": actor,
                "callId": call,
                "x-codex-turn-metadata": {}
            })
            .as_object()
            .expect("test metadata is an object"),
        )
        .expect("test candidate is valid")
    }

    /// Builds one Claude pre-hook whose actor is either its root session or explicit child ID.
    fn claude_pre(session: &str, agent: Option<&str>, call: &str) -> HookEvent {
        parse_claude_hook_event(
            json!({
                "hook_event_name": "PreToolUse",
                "session_id": session,
                "agent_id": agent,
                "tool_use_id": call
            })
            .to_string()
            .as_bytes(),
        )
        .expect("test hook is valid")
    }

    /// Builds one parser-shaped Codex lifecycle event for an exact actor and call.
    fn codex_hook(phase: &str, actor: &str, call: &str) -> HookEvent {
        parse_hook_event(
            json!({
                "hook_event_name": phase,
                "session_id": actor,
                "tool_use_id": call
            })
            .to_string()
            .as_bytes(),
        )
        .expect("test hook is valid")
    }

    /// Same, with the post-phase tool name the host relays for a real MCP tool call.
    fn codex_hook_with_tool(phase: &str, actor: &str, call: &str, tool: &str) -> HookEvent {
        parse_hook_event(
            json!({
                "hook_event_name": phase,
                "session_id": actor,
                "tool_use_id": call,
                "tool_name": tool
            })
            .to_string()
            .as_bytes(),
        )
        .expect("test hook is valid")
    }

    /// Direct managed Codex binding needs no hook, rejects replay, and isolates actors by channel.
    #[test]
    fn managed_codex_binding_is_direct_replay_safe_and_actor_isolated() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("managed-channel");
        let BindingStatus::Validated(started) = guard
            .establish_managed_codex_start(codex_candidate("actor-a", "start"), channel.clone())
        else {
            panic!("managed start must bind directly");
        };
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-a", "context"),
                channel.clone()
            ),
            BindingStatus::Validated(_)
        ));
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-a", "context"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-b", "context"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::InactiveBinding)
        ));
        assert!(matches!(
            guard.establish_start(codex_candidate("actor-b", "legacy"), channel),
            BindingStatus::Unavailable(BindingUnavailable::MissingPre)
        ));
        guard.stop_binding(started.binding_ref()).unwrap();
    }

    /// Retains the validated root session and post-phase tool name with the Claude parser's
    /// bounds, while the actor stays `agent_id.unwrap_or(session_id)`.
    #[test]
    fn codex_hooks_retain_root_session_and_post_tool_name_only() {
        let child = parse_hook_event(
            br#"{"hook_event_name":"PostToolUse","session_id":"root-session","agent_id":"child-thread","tool_use_id":"call","tool_name":"Bash"}"#,
        )
        .expect("test hook is valid");
        assert_eq!(child.actor_id(), "child-thread");
        assert_eq!(child.session_id(), Some("root-session"));
        assert_eq!(child.tool_name(), Some("Bash"));
        let root = parse_hook_event(
            br#"{"hook_event_name":"PostToolUseFailure","session_id":"root-session","tool_use_id":"call","tool_name":"apply_patch"}"#,
        )
        .expect("test hook is valid");
        assert_eq!(root.actor_id(), "root-session");
        assert_eq!(root.session_id(), Some("root-session"));
        assert_eq!(root.tool_name(), Some("apply_patch"));
        let pre = parse_hook_event(
            br#"{"hook_event_name":"PreToolUse","session_id":"root-session","tool_use_id":"call","tool_name":"Bash"}"#,
        )
        .expect("test hook is valid");
        assert_eq!(pre.tool_name(), None);
        // An over-bound tool name is dropped, never rejected and never truncated.
        let unnamed = parse_hook_event(
            json!({"hook_event_name":"PostToolUse","session_id":"root-session","tool_use_id":"call",
                "tool_name":"x".repeat(MAX_IDENTIFIER_BYTES + 1)})
            .to_string()
            .as_bytes(),
        )
        .expect("test hook is valid");
        assert_eq!(unnamed.tool_name(), None);
        assert!(
            parse_hook_event(
                br#"{"hook_event_name":"PostToolUse","session_id":"","tool_use_id":"c"}"#
            )
            .is_err()
        );
    }

    /// Accepts a full realistic codex-cli 0.155.1 hook payload and retains only selected fields.
    #[test]
    fn codex_parser_drops_every_unselected_real_host_field() {
        let event = parse_hook_event(
            br#"{"hook_event_name":"PostToolUse","session_id":"0f1croot","tool_use_id":"call-7",
                "tool_name":"Bash","cwd":"/Users/u/secret-project","model":"gpt-5.3",
                "permission_mode":"workspace-write","transcript_path":"/Users/u/.codex/t.jsonl",
                "turn_id":"turn-91","agent_type":"full-access",
                "tool_input":{"command":"printf secret"},
                "tool_response":{"exit_code":0,"output":"secret"}}"#,
        )
        .expect("realistic payload is valid");
        assert_eq!(event.host(), HostKind::Codex);
        assert_eq!(event.phase(), HookPhase::Post);
        assert_eq!(event.actor_id(), "0f1croot");
        assert_eq!(event.session_id(), Some("0f1croot"));
        assert_eq!(event.call_id(), "call-7");
        assert_eq!(event.tool_name(), Some("Bash"));
        let debug = format!("{event:?}");
        for secret in [
            "secret",
            "gpt-5.3",
            "transcript",
            "turn-91",
            "workspace-write",
            "full-access",
        ] {
            assert!(!debug.contains(secret), "{debug}");
        }
    }

    /// Pins the managed pairing state machine (T29B §4): managed MCP admission consumes its
    /// paired exact pre-observation and silences its own post, while duplicate pres, completed
    /// call IDs, conflicting settling state and pre-less native posts stay rejected.
    #[test]
    fn managed_codex_admission_consumes_a_paired_pre_and_keeps_rejections() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("managed-pair-channel");
        assert!(matches!(
            guard.establish_managed_codex_start(
                codex_candidate("actor-a", "start"),
                channel.clone()
            ),
            BindingStatus::Validated(_)
        ));
        // Native pre buffered before the managed call for the same invocation: permitted, consumed.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-1"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        let BindingStatus::Validated(call) = guard
            .validate_managed_codex_active(codex_candidate("actor-a", "call-1"), channel.clone())
        else {
            panic!("a paired native pre must not reject managed admission");
        };
        assert_eq!(call.call_id(), "call-1");
        // The MCP call's own later native post is an ordinary completed replay: silent.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PostToolUse", "actor-a", "call-1"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        // A duplicated pre-event poisons the invocation permanently, for hooks and admission alike.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-2"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-2"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-a", "call-2"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        // A call settling through legacy MCP correlation conflicts with managed admission.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-3"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start(codex_candidate("actor-a", "call-3"), channel.clone()),
            BindingStatus::Validated(_)
        ));
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-a", "call-3"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        // A native post without a matching pre never yields NativeObserved or a settling.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PostToolUse", "actor-a", "call-4"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Mismatch)
        ));
        // Replayed managed admission of a completed call ID stays permanently rejected.
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-a", "call-1"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        // Native-only pairing for a bound actor still coalesces its own hint: Pre then Post.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-5"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.observe_hook(codex_hook("PostToolUse", "actor-a", "call-5"), channel),
            BindingStatus::NativeObserved(_)
        ));
    }

    /// A self-MCP post pairing a still-buffered pre — a call rejected before managed admission —
    /// is recorded rejected and stays silent with no native hint, while a genuine native pairing
    /// on the same binding still observes (T29B final review 4).
    #[test]
    fn rejected_self_mcp_calls_never_become_native_observations() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("rejected-self-channel");
        let BindingStatus::Validated(started) = guard
            .establish_managed_codex_start(codex_candidate("actor-a", "start"), channel.clone())
        else {
            panic!("managed start must bind directly");
        };
        // Pre buffered, then the MCP call is rejected before admission (invalid arguments never
        // reach IPC): the pre stays buffered and no completion was ever recorded.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-9"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        // The post names this product's own MCP tool: a silent rejection, not NativeObserved.
        assert!(matches!(
            guard.observe_hook(
                codex_hook_with_tool(
                    "PostToolUse",
                    "actor-a",
                    "call-9",
                    "mcp__agent_ide__context"
                ),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::MissingInvocation)
        ));
        // No native epoch advance: the active generation coalesced no change hint.
        assert_eq!(
            guard.take_native_change_hint(started.binding_ref()),
            Ok(false)
        );
        // The rejected call id is permanent replay evidence for hooks and admission alike.
        assert!(matches!(
            guard.observe_hook(
                codex_hook_with_tool(
                    "PostToolUse",
                    "actor-a",
                    "call-9",
                    "mcp__agent_ide__context"
                ),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Mismatch)
        ));
        assert!(matches!(
            guard.validate_managed_codex_active(
                codex_candidate("actor-a", "call-9"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        // The hyphenated self spelling is equally excluded; a genuine native pairing on this
        // binding still observes it.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "call-10"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.observe_hook(
                codex_hook_with_tool("PostToolUse", "actor-a", "call-10", "Bash"),
                channel
            ),
            BindingStatus::NativeObserved(_)
        ));
    }

    /// Both plate carriers resolve one binding fingerprint (T29B §5): the paired native post's
    /// `NativeObserved` binding is exactly the active generation a managed reply validates,
    /// because hook actor, channel (same published attachment), and generation all coincide —
    /// the feed's `(fingerprint, worktree)` key is therefore shared and deduplicates.
    #[test]
    fn native_post_and_managed_reply_resolve_one_fingerprint() {
        // The carrier policy is decided only here, and only via the capability predicates.
        assert_eq!(HostKind::Claude.feed_delivery(), FeedDelivery::Hooks);
        let delivery = HostKind::Codex.feed_delivery();
        assert_eq!(delivery, FeedDelivery::HooksAndReplies);
        assert!(delivery.allows_hooks() && delivery.allows_replies());
        assert!(!FeedDelivery::Hooks.allows_replies());
        assert!(!FeedDelivery::Replies.allows_hooks());

        let mut guard = HostBindingGuard::default();
        let channel = channel("dedup-channel");
        let BindingStatus::Validated(started) = guard
            .establish_managed_codex_start(codex_candidate("actor-a", "start"), channel.clone())
        else {
            panic!("managed start must bind directly");
        };
        // A paired native Pre/Post with no MCP call resolves the already-active generation and
        // never mints a new one.
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "edit-1"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        let BindingStatus::NativeObserved(observed) = guard.observe_hook(
            codex_hook("PostToolUse", "actor-a", "edit-1"),
            channel.clone(),
        ) else {
            panic!("a paired native post must observe the active binding");
        };
        assert_eq!(
            observed.fingerprint(),
            started.binding_ref().fingerprint(),
            "the native post must reuse the active generation's fingerprint"
        );
        // An ordinary managed call validates that same generation, so its reply delivery shares
        // the feed key with anything the native post already delivered.
        let BindingStatus::Validated(call) =
            guard.validate_managed_codex_active(codex_candidate("actor-a", "context"), channel)
        else {
            panic!("ordinary managed admission must validate");
        };
        assert_eq!(
            call.binding_ref().fingerprint(),
            observed.fingerprint(),
            "reply and hook carriers must share one feed key"
        );
    }

    /// Caps pending calls per exact scope so one actor cannot deny a peer in the same channel.
    #[test]
    fn pending_capacity_is_actor_local_and_survives_missing_post() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("pending-channel");
        for index in 0..MAX_PENDING_PER_SCOPE {
            let call = format!("actor-a-{index}");
            assert!(matches!(
                guard.observe_hook(codex_hook("PreToolUse", "actor-a", &call), channel.clone()),
                BindingStatus::PreObserved
            ));
        }
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-a", "over-limit"),
                channel.clone()
            ),
            BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded)
        ));
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PreToolUse", "actor-b", "start"),
                channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start(codex_candidate("actor-b", "start"), channel),
            BindingStatus::Validated(_)
        ));
    }

    /// Settles terminal failures with a hint while exact permission denial only rejects its pre-hook.
    #[test]
    fn terminal_failure_and_permission_denial_have_distinct_hint_semantics() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("terminal-channel");
        assert!(matches!(
            guard.observe_hook(codex_hook("PreToolUse", "actor", "start"), channel.clone()),
            BindingStatus::PreObserved
        ));
        let BindingStatus::Validated(started) =
            guard.establish_start(codex_candidate("actor", "start"), channel.clone())
        else {
            panic!("start must validate");
        };
        assert!(matches!(
            guard.observe_hook(codex_hook("PostToolUse", "actor", "start"), channel.clone()),
            BindingStatus::Settled(_)
        ));
        assert!(matches!(
            guard.observe_hook(codex_hook("PreToolUse", "actor", "failed"), channel.clone()),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.validate_active(codex_candidate("actor", "failed"), channel.clone()),
            BindingStatus::Validated(_)
        ));
        assert!(matches!(
            guard.observe_hook(
                codex_hook("PostToolUseFailure", "actor", "failed"),
                channel.clone()
            ),
            BindingStatus::Settled(_)
        ));
        assert!(
            guard
                .take_native_change_hint(started.binding_ref())
                .unwrap()
        );
        assert!(matches!(
            guard.observe_hook(codex_hook("PreToolUse", "actor", "denied"), channel.clone()),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.validate_active(codex_candidate("actor", "denied"), channel.clone()),
            BindingStatus::Validated(_)
        ));
        assert!(matches!(
            guard.observe_hook(codex_hook("PermissionDenied", "actor", "denied"), channel),
            BindingStatus::Unavailable(BindingUnavailable::MissingInvocation)
        ));
        assert!(
            !guard
                .take_native_change_hint(started.binding_ref())
                .unwrap()
        );
    }

    /// Retains a validated call's replay authority across stop until the daemon guard is dropped.
    #[test]
    fn validated_call_cannot_be_replayed_after_stop() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("stop-replay-channel");
        assert!(matches!(
            guard.observe_hook(codex_hook("PreToolUse", "actor", "start"), channel.clone()),
            BindingStatus::PreObserved
        ));
        let BindingStatus::Validated(started) =
            guard.establish_start(codex_candidate("actor", "start"), channel.clone())
        else {
            panic!("start must validate");
        };
        guard.stop_binding(started.binding_ref()).unwrap();
        assert!(matches!(
            guard.observe_hook(codex_hook("PreToolUse", "actor", "start"), channel),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
    }

    /// Claude Stop closes a concurrently pre-observed Edit while retaining exact cleanup access.
    #[test]
    fn claude_stop_closes_concurrent_edit_admission_before_cleanup() {
        let mut guard = HostBindingGuard::default();
        let channel = channel("claude-stop-channel");
        assert!(matches!(
            guard.observe_hook(claude_pre("actor", None, "start"), channel.clone()),
            BindingStatus::PreObserved
        ));
        let BindingStatus::Validated(started) =
            guard.establish_start_claude("start", channel.clone())
        else {
            panic!("Claude start must validate");
        };
        for call in ["edit", "stop"] {
            assert!(matches!(
                guard.observe_hook(claude_pre("actor", None, call), channel.clone()),
                BindingStatus::PreObserved
            ));
        }
        let BindingStatus::Validated(stop) = guard.validate_active_claude("stop", channel.clone())
        else {
            panic!("Claude stop must validate");
        };
        guard.begin_stop(stop.binding_ref()).unwrap();
        assert!(matches!(
            guard.validate_active_claude("edit", channel),
            BindingStatus::Unavailable(BindingUnavailable::InactiveBinding)
        ));
        assert!(guard.consume_active(started.binding_ref()).is_err());
        assert_eq!(
            guard
                .consume_stopping(started.binding_ref())
                .unwrap()
                .binding_ref(),
            started.binding_ref()
        );
        guard.stop_binding(started.binding_ref()).unwrap();
        assert!(guard.consume_stopping(started.binding_ref()).is_err());
    }

    /// Rejects mixed and partial host-shaped metadata instead of selecting a convenient parser.
    #[test]
    fn host_metadata_selection_requires_exactly_one_complete_contract() {
        for metadata in [
            json!({}),
            json!({"threadId":"actor"}),
            json!({"claudecode/toolUseId":"call","threadId":"actor"}),
            json!({"claudecode/toolUseId":"call","x-codex-turn-metadata":{}}),
            json!({"claudecode/toolUseId":"call","codex/sandbox-state-meta":{}}),
        ] {
            assert!(matches!(
                parse_host_kind(metadata.as_object().expect("test metadata is an object")),
                Err(BindingUnavailable::InvalidMetadata) | Err(BindingUnavailable::MissingField(_))
            ));
        }
        assert_eq!(
            parse_host_kind(
                json!({"claudecode/toolUseId":"call","progressToken":1})
                    .as_object()
                    .expect("test metadata is an object")
            ),
            Ok(HostKind::Claude)
        );
        assert_eq!(
            parse_host_kind(
                json!({"threadId":"actor","callId":"call","x-codex-turn-metadata":{}})
                    .as_object()
                    .expect("test metadata is an object")
            ),
            Ok(HostKind::Codex)
        );
    }

    /// Consumes one unique same-channel Claude pre-hook and rejects missing or ambiguous matches.
    #[test]
    fn claude_start_recovers_one_exact_parent_or_child_pre_observation() {
        let mut guard = HostBindingGuard::default();
        let first_channel = channel("first-channel");
        let other_channel = channel("other-channel");
        assert!(matches!(
            guard.establish_start_claude("missing", first_channel.clone()),
            BindingStatus::Unavailable(BindingUnavailable::MissingPre)
        ));
        assert!(matches!(
            guard.observe_hook(
                claude_pre("session", None, "parent-call"),
                first_channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start_claude("parent-call", other_channel),
            BindingStatus::Unavailable(BindingUnavailable::MissingPre)
        ));
        assert!(matches!(
            guard.establish_start_claude("parent-call", first_channel.clone()),
            BindingStatus::Validated(_)
        ));
        assert!(matches!(
            guard.establish_start_claude("parent-call", first_channel.clone()),
            BindingStatus::Unavailable(BindingUnavailable::MissingPre)
        ));

        let child_channel = channel("child-channel");
        assert!(matches!(
            guard.observe_hook(
                claude_pre("session", Some("only-child"), "child-call"),
                child_channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        let BindingStatus::Validated(child) =
            guard.establish_start_claude("child-call", child_channel)
        else {
            panic!("one exact child pre-hook must validate");
        };
        assert_eq!(child.actor_id(), "only-child");

        for agent in ["child-a", "child-b"] {
            assert!(matches!(
                guard.observe_hook(
                    claude_pre("session", Some(agent), "shared-call"),
                    first_channel.clone()
                ),
                BindingStatus::PreObserved
            ));
        }
        assert!(matches!(
            guard.establish_start_claude("shared-call", first_channel),
            BindingStatus::Unavailable(BindingUnavailable::Mismatch)
        ));

        let mut duplicate = HostBindingGuard::default();
        let duplicate_channel = channel("duplicate-channel");
        let event = claude_pre("session", Some("child"), "duplicate-call");
        assert!(matches!(
            duplicate.observe_hook(event.clone(), duplicate_channel.clone()),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            duplicate.observe_hook(event, duplicate_channel.clone()),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
        assert!(matches!(
            duplicate.establish_start_claude("duplicate-call", duplicate_channel),
            BindingStatus::Unavailable(BindingUnavailable::MissingPre)
        ));
    }

    /// Fences a saturated scope while preserving unrelated Codex and Claude correlation capacity.
    #[test]
    fn rejection_saturation_is_scoped_and_requires_a_fresh_scope() {
        let mut guard = HostBindingGuard::default();
        let noisy = channel("noisy-channel");
        for index in 0..MAX_REPLAYS_PER_SCOPE {
            assert!(matches!(
                guard.establish_start(
                    codex_candidate("noisy-actor", &format!("rejected-{index}")),
                    noisy.clone()
                ),
                BindingStatus::Unavailable(BindingUnavailable::MissingPre)
            ));
        }
        assert!(matches!(
            guard.establish_start(codex_candidate("noisy-actor", "over-budget"), noisy.clone()),
            BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded)
        ));
        assert!(matches!(
            guard.observe_hook(
                parse_hook_event(
                    br#"{"hook_event_name":"PreToolUse","session_id":"noisy-actor","tool_use_id":"valid"}"#
                )
                .expect("test hook is valid"),
                noisy
            ),
            BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded)
        ));

        let codex_channel = channel("fresh-codex-channel");
        assert!(matches!(
            guard.observe_hook(
                parse_hook_event(
                    br#"{"hook_event_name":"PreToolUse","session_id":"codex-actor","tool_use_id":"start"}"#
                )
                .expect("test hook is valid"),
                codex_channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start(codex_candidate("codex-actor", "start"), codex_channel),
            BindingStatus::Validated(_)
        ));

        let claude_channel = channel("fresh-claude-channel");
        assert!(matches!(
            guard.observe_hook(
                claude_pre("claude-session", None, "start"),
                claude_channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start_claude("start", claude_channel),
            BindingStatus::Validated(_)
        ));
    }

    /// Caps scopes within one channel without consuming an unrelated channel's scope budget.
    #[test]
    fn replay_scope_allocation_is_partitioned_by_channel() {
        let mut guard = HostBindingGuard::default();
        let noisy_channel = channel("many-scopes-channel");
        for index in 0..MAX_REPLAY_SCOPES_PER_CHANNEL {
            assert!(matches!(
                guard.establish_start(
                    codex_candidate(&format!("actor-{index}"), "rejected"),
                    noisy_channel.clone()
                ),
                BindingStatus::Unavailable(BindingUnavailable::MissingPre)
            ));
        }
        assert!(matches!(
            guard.establish_start(codex_candidate("new-actor", "rejected"), noisy_channel),
            BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded)
        ));

        let unrelated = channel("unrelated-channel");
        assert!(matches!(
            guard.observe_hook(
                parse_hook_event(
                    br#"{"hook_event_name":"PreToolUse","session_id":"unrelated","tool_use_id":"start"}"#
                )
                .expect("test hook is valid"),
                unrelated.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start(codex_candidate("unrelated", "start"), unrelated),
            BindingStatus::Validated(_)
        ));
    }

    /// Keeps total channel, scope, and record counts within their explicit product bounds.
    #[test]
    fn replay_ledger_has_fixed_total_bounds_without_eviction() {
        let mut guard = HostBindingGuard::default();
        for index in 0..MAX_REPLAY_CHANNELS {
            assert!(matches!(
                guard.establish_start(
                    codex_candidate("actor", "rejected"),
                    channel(&format!("channel-{index}"))
                ),
                BindingStatus::Unavailable(BindingUnavailable::MissingPre)
            ));
        }
        assert_eq!(guard.replays.len(), MAX_REPLAY_CHANNELS);
        assert_eq!(
            guard
                .replays
                .values()
                .flat_map(BTreeMap::values)
                .map(BTreeMap::len)
                .sum::<usize>(),
            MAX_REPLAY_CHANNELS
        );
        assert!(matches!(
            guard.establish_start(
                codex_candidate("actor", "rejected"),
                channel("over-channel-budget")
            ),
            BindingStatus::Unavailable(BindingUnavailable::CapacityExceeded)
        ));
        assert!(matches!(
            guard.establish_start(codex_candidate("actor", "rejected"), channel("channel-0")),
            BindingStatus::Unavailable(BindingUnavailable::Replay)
        ));
    }

    /// Settles more than the former global limit while keeping a fresh Claude scope usable.
    #[test]
    fn completed_replays_do_not_exhaust_unrelated_host_scopes() {
        let mut guard = HostBindingGuard::default();
        let codex_channel = channel("settled-codex-channel");
        for actor_index in 0..17 {
            let actor = format!("actor-{actor_index}");
            for call_index in 0..MAX_REPLAYS_PER_SCOPE {
                let call = format!("call-{call_index}");
                let pre = parse_hook_event(
                    json!({
                        "hook_event_name": "PreToolUse",
                        "session_id": actor,
                        "tool_use_id": call
                    })
                    .to_string()
                    .as_bytes(),
                )
                .expect("test pre-hook is valid");
                assert!(matches!(
                    guard.observe_hook(pre, codex_channel.clone()),
                    BindingStatus::PreObserved
                ));
                let candidate = codex_candidate(&actor, &call);
                let status = if call_index == 0 {
                    guard.establish_start(candidate, codex_channel.clone())
                } else {
                    guard.validate_active(candidate, codex_channel.clone())
                };
                assert!(matches!(status, BindingStatus::Validated(_)));
                let post = parse_hook_event(
                    json!({
                        "hook_event_name": "PostToolUse",
                        "session_id": actor,
                        "tool_use_id": call
                    })
                    .to_string()
                    .as_bytes(),
                )
                .expect("test post-hook is valid");
                assert!(matches!(
                    guard.observe_hook(post, codex_channel.clone()),
                    BindingStatus::Settled(_)
                ));
            }
        }

        let claude_channel = channel("unrelated-claude-channel");
        assert!(matches!(
            guard.observe_hook(
                claude_pre("claude-session", None, "start"),
                claude_channel.clone()
            ),
            BindingStatus::PreObserved
        ));
        assert!(matches!(
            guard.establish_start_claude("start", claude_channel),
            BindingStatus::Validated(_)
        ));
    }
}
